const CACHE='pilotdesk-v19';
const CORE=['/','/index.html','/404.html','/about.html','/airport.html','/flights.html','/flight-brief.html','/metar-decoder.html','/aircraft.html','/guides.html','/guides/metar-taf.html','/guides/flight-planning.html','/weight-balance.html','/history.html','/changelog.html','/planner.html','/route-planner.html','/procedures.html','/poh-chart-studio.html','/checklist-trainer.html','/assets/styles.css','/assets/hub.css','/assets/wb-v2.css','/assets/wb-cabin.css','/assets/route-planner.css','/assets/planner-suite.css','/assets/procedure-viewer.css','/assets/checklist-trainer.css','/assets/weather.css','/assets/site.js','/assets/product-nav.js','/assets/airport.js','/assets/flights.js','/assets/flight-brief.js','/assets/route-save.js','/assets/metar-decoder.js','/assets/safety.js','/assets/ad-config.js','/assets/ads.js','/assets/global-nav.js','/assets/analytics.js','/assets/features.js','/assets/share-enhance.js','/assets/calculator-ux.js','/assets/theme.js','/assets/offline-weather.js','/assets/aircraft-v2.js','/assets/aircraft-transfer.js','/assets/aircraft-training.js','/assets/wb-export.js','/assets/update.js','/assets/errors.js','/assets/seo.js','/assets/product-polish.js','/assets/runtime-qol.js','/assets/pilotdesk-plus.js','/assets/navlog-core.js','/assets/checklist-trainer.js','/assets/poh-chart-studio.js','/assets/route-planner.js','/assets/procedures.js','/assets/wb-cabin.js','/assets/icon.svg','/site.webmanifest'];
const cacheable=r=>r&&r.ok&&(r.type==='basic'||r.type==='default');
async function put(cache,req,res){if(cacheable(res))await cache.put(req,res.clone());return res}
async function precache(){const cache=await caches.open(CACHE);await cache.addAll(CORE);try{const r=await fetch('/sitemap.xml',{cache:'no-store'});if(r.ok){const xml=await r.text(),urls=[...xml.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>new URL(m[1]).pathname).filter(p=>!p.startsWith('/api/')&&!p.startsWith('/_vercel/')&&p!=='/weather.html');await Promise.allSettled([...new Set(urls)].map(async p=>{const req=new Request(p,{credentials:'same-origin'});const res=await fetch(req);if(cacheable(res))await cache.put(req,res)}))}}catch{}}
self.addEventListener('install',e=>e.waitUntil((async()=>{await precache();await self.skipWaiting()})()));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('activate',e=>e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('pilotdesk-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})()));
async function networkFirst(req){const cache=await caches.open(CACHE);try{const res=await fetch(req,{cache:'no-store'});return put(cache,req,res)}catch{return (await cache.match(req))||(await cache.match(new URL(req.url).pathname))||(await cache.match('/404.html'))||(await cache.match('/index.html'))}}
async function staleWhileRevalidate(req){const cache=await caches.open(CACHE),hit=await cache.match(req);const fresh=fetch(req).then(r=>put(cache,req,r)).catch(()=>null);return hit||(await fresh)||Response.error()}
async function cacheFirst(req){const cache=await caches.open(CACHE),hit=await cache.match(req);if(hit)return hit;try{return put(cache,req,await fetch(req))}catch{return Response.error()}}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;if(url.pathname.startsWith('/api/')||url.pathname.startsWith('/_vercel/'))return;if(req.mode==='navigate'){event.respondWith(networkFirst(req));return}if(['/assets/weather-fixed.js','/assets/weather-extra.js','/assets/product-nav.js','/assets/airport.js','/assets/flights.js','/assets/flight-brief.js','/assets/route-save.js','/assets/aircraft-v2.js'].includes(url.pathname)){event.respondWith(networkFirst(req));return}if(/\.(?:js|css|svg|png|jpg|jpeg|webp|woff2?)$/i.test(url.pathname)){event.respondWith(staleWhileRevalidate(req));return}event.respondWith(cacheFirst(req))});
