import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Track="ppl"|"cpl"|"atp";
type Question={id:string;area:string;acs:string;prompt:string;options:string[];correct:number;explanation:string;source:"faa-sample-derived"|"pilotdesk-acs";sourceUrl?:string};

const FAA_PAR="https://www.faa.gov/sites/faa.gov/files/training_testing/testing/test_questions/par_questions.pdf";
const FAA_CAX="https://www.faa.gov/sites/faa.gov/files/training_testing/testing/test_questions/cax_questions.pdf";
const FAA_ATM="https://www.faa.gov/sites/faa.gov/files/training_testing/testing/test_questions/atm_questions.pdf";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const json=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers:cors});

const banks:Record<Track,Question[]>={
 ppl:[
  {id:"ppl-categories",area:"Regulations & Airspace",acs:"PA.I.A.K1",prompt:"Which list contains aircraft categories rather than aircraft classes?",options:["Single-engine land, multiengine land, single-engine sea","Airplane, rotorcraft, glider, lighter-than-air","Gyroplane, helicopter, airship, free balloon"],correct:1,explanation:"Airplane, rotorcraft, glider, and lighter-than-air are aircraft categories. Single-engine land/sea and multiengine land/sea are classes within the airplane category.",source:"faa-sample-derived",sourceUrl:FAA_PAR},
  {id:"ppl-classg-vis",area:"Regulations & Airspace",acs:"PA.I.E.K1",prompt:"During daytime VFR in Class G airspace above 1,200 feet AGL but below 10,000 feet MSL, what minimum flight visibility applies?",options:["1 statute mile","3 statute miles","5 statute miles"],correct:0,explanation:"For day VFR in Class G in that altitude band, the minimum flight visibility is 1 statute mile. Always verify current 14 CFR 91.155 before flight.",source:"faa-sample-derived",sourceUrl:FAA_PAR},
  {id:"ppl-light-signal",area:"Airport Operations",acs:"PA.III.A.K3",prompt:"While taxiing, what does a flashing white light gun signal from the tower mean?",options:["Clear the runway immediately","Taxi clear of the landing area","Return to the starting point on the airport"],correct:2,explanation:"A flashing white light to an aircraft on the ground means return to the starting point on the airport.",source:"faa-sample-derived",sourceUrl:FAA_PAR},
  {id:"ppl-runway-crossing",area:"Airport Operations",acs:"PA.III.A.K2",prompt:"At a towered airport, what must you have before crossing an assigned runway hold-short line?",options:["An explicit runway-crossing or takeoff clearance as applicable","Only a taxi clearance to the runway","A transponder code"],correct:0,explanation:"Do not cross a runway hold-short line at a towered airport without the applicable explicit ATC clearance.",source:"pilotdesk-acs"},
  {id:"ppl-temp-da",area:"Weather",acs:"PA.I.C.K3c",prompt:"With other conditions unchanged, what happens to density altitude as outside air temperature increases?",options:["It decreases","It increases","It remains equal to pressure altitude"],correct:1,explanation:"Warmer air is less dense, so density altitude increases as temperature rises, all else equal.",source:"pilotdesk-acs"},
  {id:"ppl-metar-wind",area:"Weather",acs:"PA.I.C.K2",prompt:"In a METAR, what does 18018G27KT report?",options:["Wind from 180° at 18 kt, gusting 27 kt","Wind from 018° at 27 kt","Variable wind at 18 kt"],correct:0,explanation:"The group means wind from 180 degrees true at 18 knots, gusting to 27 knots.",source:"pilotdesk-acs"},
  {id:"ppl-moment",area:"Performance & Weight/Balance",acs:"PA.I.F.K2",prompt:"How is a loading-station moment calculated?",options:["Weight × arm","Weight ÷ arm","Arm ÷ weight"],correct:0,explanation:"Moment equals weight multiplied by arm. Total CG is then found from total moment divided by total weight.",source:"pilotdesk-acs"},
  {id:"ppl-da-performance",area:"Performance & Weight/Balance",acs:"PA.I.F.K1",prompt:"As density altitude rises, a normally aspirated airplane's takeoff and climb performance generally...",options:["Improves","Degrades","Does not change"],correct:1,explanation:"Higher density altitude reduces air density and typically increases takeoff distance while reducing climb performance.",source:"pilotdesk-acs"},
  {id:"ppl-transponder",area:"Systems & Airworthiness",acs:"PA.I.B.K1b",prompt:"How often is the transponder inspection required for operations that require a transponder under 14 CFR 91.413?",options:["Every 12 calendar months","Every 24 calendar months","Every 36 calendar months"],correct:1,explanation:"The transponder must be tested and inspected within the preceding 24 calendar months for operations where the rule applies.",source:"faa-sample-derived",sourceUrl:FAA_PAR},
  {id:"ppl-static",area:"Systems & Airworthiness",acs:"PA.I.G.K1",prompt:"Which primary instruments rely on static pressure?",options:["Altimeter and VSI","Tachometer and magnetic compass","Oil pressure and ammeter"],correct:0,explanation:"The altimeter and vertical speed indicator use static pressure; the airspeed indicator uses both pitot and static pressure.",source:"pilotdesk-acs"},
  {id:"ppl-external-pressure",area:"ADM & Human Factors",acs:"PA.I.H.R3",prompt:"Weather is trending worse and you are late for an event. What is the strongest ADM response?",options:["Continue because the schedule is already committed","Reassess margins, alternates, and willingness to delay or divert","Increase speed to recover the schedule"],correct:1,explanation:"External pressure is a recognized risk. Good ADM deliberately reassesses the plan and preserves safe alternatives.",source:"pilotdesk-acs"},
  {id:"ppl-hazard-attitude",area:"ADM & Human Factors",acs:"PA.I.H.K2",prompt:"Continuing a deteriorating flight mainly because you already spent time and money getting this far is closest to...",options:["Sunk-cost thinking","Checklist discipline","Positive transfer of learning"],correct:0,explanation:"Past investment should not justify accepting new risk; that is sunk-cost thinking.",source:"pilotdesk-acs"}
 ],
 cpl:[
  {id:"cpl-class-e-vis",area:"Regulations & Commercial Ops",acs:"CA.I.E.K1",prompt:"On a VFR flight in Class E airspace above 10,000 feet MSL, what minimum flight visibility applies?",options:["3 statute miles","5 statute miles","1 statute mile"],correct:1,explanation:"Above 10,000 feet MSL in Class E, the VFR minimum flight visibility is 5 statute miles. Verify current 14 CFR 91.155 for operational use.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-part119",area:"Regulations & Commercial Ops",acs:"CA.I.A.K2",prompt:"Which example is generally among the operations excepted from the requirement to hold a Part 119 operating certificate when conducted within the rule's conditions?",options:["On-demand passenger charter","Aerial application and aerial photography","Scheduled passenger service"],correct:1,explanation:"Certain operations such as aerial work are excepted under 14 CFR 119.1(e), subject to the applicable conditions and other regulations.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-unstable-air",area:"Weather",acs:"CA.I.C.K3a",prompt:"Which air mass is most associated with atmospheric instability?",options:["Cool and dry","Warm and humid","Strongly descending air"],correct:1,explanation:"Warm, moist air is more likely to be unstable and support vertical development when lifted.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-cold-front",area:"Weather",acs:"CA.I.C.K3e",prompt:"After a fast-moving cold front passes, which conditions are commonly expected?",options:["Clearer skies, gusty/turbulent winds, and cooler temperatures","Persistent warm drizzle and fog","Calm winds and warmer temperatures"],correct:0,explanation:"Behind a fast cold front, cooler air, improving ceilings, and gusty/turbulent winds are common.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-downwind",area:"Performance & Aerodynamics",acs:"CA.IV.B.K2",prompt:"Compared with landing into the wind, a downwind landing tends to produce what effect?",options:["Greater groundspeed and a tendency to overshoot the intended point","Lower groundspeed and shorter landing distance","No meaningful change in groundspeed"],correct:0,explanation:"A tailwind raises groundspeed for a given airspeed and generally increases landing distance and overshoot tendency.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-load-factor",area:"Performance & Aerodynamics",acs:"CA.I.F.K3",prompt:"In a coordinated level 60° banked turn, a load factor of 2.0 means...",options:["The aircraft structure is carrying about twice the aircraft weight","The gust factor is twice the limit","The airplane is automatically beyond its structural limit"],correct:0,explanation:"A 2.0 load factor means the aerodynamic load is twice the aircraft weight; whether that exceeds a limit depends on the aircraft and operating category.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-carbon-monoxide",area:"Systems & Airworthiness",acs:"CA.I.G.K1i",prompt:"Why are exhaust-manifold cabin-heating systems inspected carefully?",options:["To prevent carbon monoxide from entering the cabin","To prevent the altimeter from freezing","To prevent the battery from overcharging"],correct:0,explanation:"A cracked exhaust system or heat exchanger can introduce carbon monoxide into cabin heat air.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-ad",area:"Systems & Airworthiness",acs:"CA.I.B.K1c",prompt:"You discover an applicable Airworthiness Directive is overdue before flight. What is the appropriate default decision?",options:["Fly because every AD has a 10-hour grace period","Do not operate until the aircraft complies or a specific legal provision permits operation","Fly VFR only"],correct:1,explanation:"An aircraft must comply with applicable ADs unless the AD or another specific authorization provides otherwise.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-class-b",area:"Navigation & Airspace",acs:"CA.I.E.K1",prompt:"Approach replies to your Class B entry request with your callsign and 'standby.' May you enter the Class B?",options:["Yes, because your callsign was acknowledged","No, remain outside until ATC issues an explicit Class B clearance","Yes, if ADS-B Out is operating"],correct:1,explanation:"Class B entry requires an explicit ATC clearance. An acknowledgment or 'standby' is not that clearance.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-critical-mach",area:"Navigation & Airspace",acs:"CA.I.F.K3",prompt:"Exceeding critical Mach can lead to...",options:["Reduced drag with improved control","Aircraft control difficulties from compressibility effects","A propeller governor overspeed only"],correct:1,explanation:"Shock formation and flow separation above critical Mach can produce buffet, drag rise, and control difficulties.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-preflight",area:"ADM & Operations",acs:"CA.I.C.K3",prompt:"For a VFR cross-country, what must the PIC become familiar with during preflight planning?",options:["Weather reports/forecasts, fuel requirements, alternatives, and other information appropriate to the flight","Only the destination runway length","Only the route entered in the GPS"],correct:0,explanation:"14 CFR 91.103 requires the PIC to become familiar with all available information concerning the flight, including specified planning items.",source:"faa-sample-derived",sourceUrl:FAA_CAX},
  {id:"cpl-high-performance",area:"ADM & Operations",acs:"CA.I.A.K1",prompt:"What is normally required to act as PIC of a high-performance airplane under 14 CFR 61.31?",options:["Ground and flight training in a high-performance airplane plus a logbook endorsement","Five hours as SIC in any turbine airplane","Only a complex-airplane endorsement"],correct:0,explanation:"The rule requires the appropriate ground and flight training from an authorized instructor and a logbook endorsement, unless an exception applies.",source:"faa-sample-derived",sourceUrl:FAA_CAX}
 ],
 atp:[
  {id:"atp-alternate",area:"Air Carrier Regulations",acs:"AA.I.G.K4",prompt:"For a Part 121 operation, an airport used as an alternate must meet what forecast criterion at the applicable time?",options:["The alternate weather minima specified in the operator's operations specifications","Only the lowest published IAP minimum","VFR minimums regardless of OpSpecs"],correct:0,explanation:"Part 121 alternate planning uses the applicable alternate weather minima established in the operator's operations specifications.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-dispatch",area:"Air Carrier Regulations",acs:"AA.I.E.K9",prompt:"On a Part 121 domestic flight, who shares responsibility with the PIC for preflight planning, delays, and the dispatch release?",options:["Director of operations","Aircraft dispatcher","Chief pilot"],correct:1,explanation:"For domestic Part 121 operations, the PIC and aircraft dispatcher share operational control responsibilities defined by the regulations and company system.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-slats",area:"High-Altitude Performance",acs:"AA.I.A.K12",prompt:"Extending leading-edge slats generally has what aerodynamic effect?",options:["Increases camber and maximum lift coefficient","Forces earlier airflow separation","Reduces maximum lift coefficient"],correct:0,explanation:"Leading-edge slats allow higher lift coefficients and delay separation at higher angles of attack.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-weight-climb",area:"High-Altitude Performance",acs:"AA.I.B.K2c",prompt:"How does increased aircraft weight generally affect climb performance?",options:["It increases available excess thrust","It increases drag/required lift and reduces climb performance","It has no effect above 10,000 feet"],correct:1,explanation:"More weight requires more lift and typically more induced drag, reducing excess thrust/power available for climb.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-lpv",area:"IFR & Procedures",acs:"AA.VI.E.K2",prompt:"What equipment approval is required to fly an RNAV (GPS) approach to LPV minimums?",options:["An AFM-approved GPS/WAAS installation capable of LPV","Any handheld GPS","A non-WAAS TSO-C129 GPS alone"],correct:0,explanation:"LPV guidance requires an appropriately approved WAAS-capable installation and aircraft authorization.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-holding",area:"IFR & Procedures",acs:"AA.VI.J.K1",prompt:"When using a flight director in a holding pattern, which turn limit is normally used?",options:["3° per second or 25° bank, whichever is less","3° per second or 45° bank, whichever is greater","1° per second with no bank limit"],correct:0,explanation:"The FAA sample material uses standard-rate or 25° bank, whichever is less, for this flight-director holding context.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-hypervent",area:"Human Factors & CRM",acs:"AA.I.F.K1b",prompt:"Which symptom is commonly associated with hyperventilation?",options:["Tingling sensations","A deliberately slower breathing rate","Improved peripheral vision"],correct:0,explanation:"Hyperventilation can cause tingling, lightheadedness, visual symptoms, and impaired performance.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-risk",area:"Human Factors & CRM",acs:"AA.I.F.K3",prompt:"Risk assessment is fundamentally based on which two dimensions?",options:["Likelihood and severity","Time and cost","Convenience and workload"],correct:0,explanation:"A common risk-management model evaluates the likelihood of an undesired event and the severity of its consequences.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-zero-fuel",area:"Systems & Aerodynamics",acs:"AA.I.B.K3e",prompt:"What is the principal structural purpose of a maximum zero-fuel-weight limitation?",options:["Limit wing bending loads caused by heavy fuselage payload without balancing wing fuel","Protect the landing gear from every hard landing","Prevent fuel temperature from becoming too low"],correct:0,explanation:"Zero-fuel-weight limits help control wing-root bending loads when fuselage payload is high and fuel in the wings is low.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-hot-start",area:"Systems & Aerodynamics",acs:"AA.I.A.K2",prompt:"A turbine-engine hot start can result from...",options:["Insufficient airflow because compressor/turbine rpm is too low for the fuel introduced","Excessive ram air at cruise","Insufficient fuel entering the combustor"],correct:0,explanation:"If fuel is introduced without enough airflow/rpm, turbine temperature can rise excessively during start.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-rwsl",area:"Airport & Weather Operations",acs:"AA.II.C.K3",prompt:"Runway Status Lights are driven by airport-surface surveillance such as...",options:["ASDE-X or ASSC","Only the control tower's manual light switch","The aircraft's TCAS"],correct:0,explanation:"RWSL systems use airport-surface surveillance data to provide direct runway-status indications to pilots and vehicle operators.",source:"faa-sample-derived",sourceUrl:FAA_ATM},
  {id:"atp-freezing-rain",area:"Airport & Weather Operations",acs:"AA.I.C.K3i",prompt:"What is the best general response to an encounter with freezing rain?",options:["Treat it as a serious icing hazard and exit the condition using aircraft/operator procedures","Remain because anti-ice makes freezing rain benign","Increase speed and continue without changing the plan"],correct:0,explanation:"Freezing rain can produce severe icing. Follow the aircraft and operator procedures and leave the icing environment promptly.",source:"pilotdesk-acs"}
 ]
};

const validTrack=(v:unknown):Track=>v==="cpl"?"cpl":v==="atp"?"atp":"ppl";
const publicQuestion=(q:Question)=>({id:q.id,area:q.area,acs:q.acs,prompt:q.prompt,options:q.options,source:q.source,sourceUrl:q.sourceUrl||null});
const statsRows=async(base:string,headers:Record<string,string>,userId:string,track:Track)=>{
 const r=await fetch(`${base}/rest/v1/skill_gap_stats?select=skill_area,correct_count,total_count,last_attempted_at&user_id=eq.${encodeURIComponent(userId)}&track=eq.${track}&order=skill_area.asc`,{headers});
 if(!r.ok)return [];
 const rows=await r.json();
 return rows.map((x:any)=>({area:x.skill_area,correct:x.correct_count,total:x.total_count,percent:x.total_count?Math.round((x.correct_count/x.total_count)*100):0,lastAttemptedAt:x.last_attempted_at}));
};

Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});
 if(!["GET","POST"].includes(req.method))return json(405,{error:"Method not allowed"});
 const base=(Deno.env.get("SUPABASE_URL")||"").replace(/\/+$/,'');
 const anon=Deno.env.get("SUPABASE_ANON_KEY")||"";
 const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
 if(!base||!anon||!service)return json(503,{error:"Pilot Skill Gap is not configured."});
 const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,'').trim();
 let user:any=null;
 if(token){const ur=await fetch(`${base}/auth/v1/user`,{headers:{apikey:anon,Authorization:`Bearer ${token}`}});if(ur.ok)user=await ur.json()}
 const adminHeaders={apikey:service,Authorization:`Bearer ${service}`,"Content-Type":"application/json"};

 if(req.method==="GET"){
  const url=new URL(req.url),track=validTrack(url.searchParams.get("track"));
  const questions=banks[track];
  const stats=user?await statsRows(base,adminHeaders,user.id,track):[];
  return json(200,{track,questionCount:questions.length,questions:questions.map(publicQuestion),stats,saved:Boolean(user),sourceNote:"Questions marked FAA sample-derived are paraphrased from FAA-published sample knowledge-test questions and mapped to the listed ACS code. PilotDesk does not claim access to active FAA test-bank questions."});
 }

 let body:any;try{body=await req.json()}catch{return json(400,{error:"Invalid JSON"})}
 const track=validTrack(body?.track),questions=banks[track],answers=Array.isArray(body?.answers)?body.answers:[];
 if(answers.length!==questions.length||answers.some((x:any)=>!Number.isInteger(x)))return json(400,{error:`Answer all ${questions.length} questions.`});
 const review=questions.map((q,i)=>({id:q.id,area:q.area,acs:q.acs,selected:answers[i],correctIndex:q.correct,correct:answers[i]===q.correct,explanation:q.explanation,source:q.source,sourceUrl:q.sourceUrl||null}));
 const areaMap=new Map<string,{correct:number,total:number}>();
 review.forEach(r=>{const v=areaMap.get(r.area)||{correct:0,total:0};v.total++;if(r.correct)v.correct++;areaMap.set(r.area,v)});
 const areaResults=[...areaMap.entries()].map(([area,v])=>({area,...v,percent:Math.round(v.correct/v.total*100)}));
 const score=review.filter(r=>r.correct).length;
 let stats=areaResults,saved=false;
 if(user){
  const rpc=await fetch(`${base}/rest/v1/rpc/record_skill_gap_attempt`,{method:"POST",headers:{...adminHeaders,Prefer:"return=representation"},body:JSON.stringify({p_user_id:user.id,p_track:track,p_area_results:areaResults.map(({area,correct,total})=>({area,correct,total}))})});
  if(!rpc.ok){const text=await rpc.text();return json(500,{error:"Unable to save skill-gap result.",detail:text.slice(0,240)})}
  stats=await rpc.json();saved=true;
 }
 const normalized=Array.isArray(stats)?stats:areaResults;
 const weakest=[...normalized].sort((a:any,b:any)=>(a.percent??100)-(b.percent??100)||(b.total??0)-(a.total??0))[0]||null;
 return json(200,{track,score,maxScore:questions.length,percent:Math.round(score/questions.length*100),review,areaResults,saved,stats:normalized,weakestArea:weakest?.area||null,sourceNote:"FAA sample-derived items are paraphrases of FAA-published sample questions, not claimed active knowledge-test questions."});
});
