from pathlib import Path
import re, json, subprocess, datetime

SITE='https://www.pilot-desk.com'
TODAY='2026-09-10'

# 1) Avoid duplicate client-side schema when a page already ships static JSON-LD.
p=Path('assets/seo.js')
s=p.read_text()
s=s.replace("function schema(){const p=pagePath(),h=document.querySelector('h1')?.textContent?.trim(),url=SITE+p;let data=null;", "function schema(){const p=pagePath(),h=document.querySelector('h1')?.textContent?.trim(),url=SITE+p;if(document.querySelector('script[data-pd-static-calc-schema],script[data-pd-guide-schema],script[data-pd-static-schema]'))return;let data=null;")
s=s.replace("description,potentialAction:{'@type':'SearchAction',target:SITE+'/?q={search_term_string}','query-input':'required name=search_term_string'}", "description")
s=s.replace("isAccessibleForFree:true,url,description,publisher", "isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'},url,description,publisher")
p.write_text(s)

# 2) Strengthen calculator template: valid free-app offer schema + contextual internal links.
p=Path('scripts/generate-calculator-pages.mjs')
s=p.read_text()
if 'const calcBySlug=' not in s:
    s=s.replace("const categoryFor=s=>", "const calcBySlug=new Map(calcs.map(c=>[c[0],c[2]]));\nconst categoryFor=s=>", 1)
if 'const guideFor=' not in s:
    marker="const useText={\n"
    guide_map="const guideFor={\n'crosswind':'/guides/crosswind-component.html','wind-triangle':'/guides/wind-triangle.html','pressure-altitude':'/guides/pressure-altitude.html','density-altitude':'/guides/density-altitude.html','climb-gradient':'/guides/climb-gradient.html','fpm-to-gradient':'/guides/climb-gradient.html','three-degree-descent':'/guides/three-degree-descent.html','top-of-descent':'/guides/top-of-descent.html','pivotal-altitude':'/guides/pivotal-altitude.html','standard-rate-bank':'/guides/standard-rate-turn.html','load-factor':'/guides/accelerated-stall-load-factor.html','accelerated-stall':'/guides/accelerated-stall-load-factor.html','true-airspeed':'/guides/true-airspeed-rule.html','moment-cg':'/guides/weight-and-balance.html','percent-mac':'/guides/weight-and-balance.html','ballast':'/guides/weight-and-balance.html','fuel-weight':'/guides/fuel-planning.html','fuel-required':'/guides/fuel-planning.html','endurance-range':'/guides/fuel-planning.html'};\n"
    s=s.replace(marker, guide_map+marker,1)
if 'const siblingSlugs=' not in s:
    old="for(const [slug,key,title,desc,fields,results] of calcs){const dir=path.join('calculators',slug),file=path.join(dir,'index.html');fs.mkdirSync(dir,{recursive:true});const category=categoryFor(slug),formula=formulas[key]||`${title} uses the entered values to compute the outputs shown above using standard arithmetic and aviation relationships.`;const fieldNames=fields.map(x=>x[1]).join(', '),resultNames=results.join(', ');const defaults=fields.map(x=>`${x[1]} ${x[2]}${x[3]?' '+x[3]:''}`).join('; ');"
    new="for(const [slug,key,title,desc,fields,results] of calcs){const dir=path.join('calculators',slug),file=path.join(dir,'index.html');fs.mkdirSync(dir,{recursive:true});const category=categoryFor(slug),formula=formulas[key]||`${title} uses the entered values to compute the outputs shown above using standard arithmetic and aviation relationships.`;const fieldNames=fields.map(x=>x[1]).join(', '),resultNames=results.join(', ');const defaults=fields.map(x=>`${x[1]} ${x[2]}${x[3]?' '+x[3]:''}`).join('; ');const siblingSlugs=(categories[category]||[]).filter(x=>x!==slug);const start=Math.max(0,(categories[category]||[]).indexOf(slug));const relatedSlugs=[...siblingSlugs.slice(start,start+3),...siblingSlugs.slice(0,3)].slice(0,3);const relatedLinks=relatedSlugs.map(x=>`<a href=\"/calculators/${x}/\">${esc(calcBySlug.get(x)||x)}</a>`).join('');const guideLink=guideFor[slug]?`<a href=\"${guideFor[slug]}\">Read the related guide</a>`:'';"
    if old not in s: raise SystemExit('calculator loop marker not found')
    s=s.replace(old,new,1)
s=s.replace('<summary><strong>Show formula and assumptions</strong></summary>', '<summary><strong>${esc(title)} formula and assumptions</strong></summary>')
s=s.replace('<div class="related"><a href="/weather.html">Live airport weather</a><a href="/guides.html">Pilot math guides</a><a href="/">All calculators</a></div>', '<div class="related">${relatedLinks}${guideLink}<a href="/guides/pilot-math-formulas.html">Pilot math formula reference</a><a href="/guides.html">All aviation guides</a></div>')
s=s.replace("isAccessibleForFree:true,url:`https://www.pilot-desk.com/calculators/${slug}/`", "isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'},url:`https://www.pilot-desk.com/calculators/${slug}/`")
p.write_text(s)

# Helpers for static guide markup.
def first_commit_date(path):
    try:
        out=subprocess.check_output(['git','log','--follow','--diff-filter=A','--format=%cs','--',path],text=True).strip().splitlines()
        return out[-1] if out else TODAY
    except Exception:
        return TODAY

def strip_article_jsonld(html):
    pat=re.compile(r'<script type="application/ld\+json"[^>]*>(.*?)</script>',re.S)
    def repl(m):
        body=m.group(1)
        if '"@type":"Article"' in body or '"@type": "Article"' in body:
            return ''
        return m.group(0)
    return pat.sub(repl,html)

def ensure_guide_schema(path):
    p=Path(path); s=p.read_text()
    title_m=re.search(r'<title>(.*?)</title>',s,re.S)
    desc_m=re.search(r'<meta name="description" content="([^"]*)">',s,re.S)
    h1_m=re.search(r'<h1>(.*?)</h1>',s,re.S)
    if not (title_m and desc_m and h1_m): return
    headline=re.sub(r'<[^>]+>','',h1_m.group(1)).strip()
    desc=desc_m.group(1)
    published=first_commit_date(path)
    org={'@type':'Organization','name':'PilotDesk','url':SITE+'/','logo':{'@type':'ImageObject','url':SITE+'/assets/icon.svg'}}
    article={'@context':'https://schema.org','@type':'Article','headline':headline,'description':desc,'datePublished':published,'dateModified':TODAY,'mainEntityOfPage':SITE+'/'+path,'author':org,'publisher':org}
    crumbs={'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Guides','item':SITE+'/guides.html'},{'@type':'ListItem','position':2,'name':headline,'item':SITE+'/'+path}]}
    s=strip_article_jsonld(s)
    s=re.sub(r'<script type="application/ld\+json" data-pd-guide-breadcrumbs="1">.*?</script>','',s,flags=re.S)
    tags=f'<script type="application/ld+json" data-pd-guide-schema="1">{json.dumps(article,separators=(",",":"))}</script><script type="application/ld+json" data-pd-guide-breadcrumbs="1">{json.dumps(crumbs,separators=(",",":"))}</script>'
    s=s.replace('</head>',tags+'</head>',1)
    p.write_text(s)

# 3) Add useful detail to the remaining short guides. These are real explanations, not keyword blocks.
extras={
'guides/pressure-altitude.html': '<h2>Pressure altitude versus indicated altitude</h2><p>Indicated altitude is what the altimeter shows after you set the local altimeter setting. Pressure altitude uses the standard 29.92 inHg reference instead. That standard reference is why pressure altitude is useful in performance calculations: it gives the aircraft performance chart a common pressure datum. When the local pressure is lower than standard, pressure altitude rises above field elevation; when local pressure is higher, pressure altitude falls below it.</p>',
'guides/three-degree-descent.html': '<h2>Why the groundspeed × 5 shortcut is close</h2><p>The exact geometry of a 3° path works out to a little more than five times groundspeed when the answer is expressed in feet per minute. That is why the cockpit rule is fast and usually close enough for a first estimate. The exact value and the shortcut separate more as groundspeed rises, so the calculator is useful when you want a tighter planning number or a quick reasonableness check.</p>',
'guides/pivotal-altitude.html': '<h2>Keep the units straight</h2><p>The common 11.3 divisor is tied to groundspeed in knots and an answer in feet AGL. Changing the speed unit changes the constant. It is also easy to accidentally use indicated airspeed when the maneuver depends on groundspeed. If the wind changes your groundspeed around the point, the pivotal altitude changes with it, which is why the visual reference remains more important than memorizing one fixed altitude.</p>',
'guides/climb-gradient.html': '<h2>Worked climb-gradient example</h2><p>A 200 ft/NM requirement at 90 knots groundspeed needs about 300 feet per minute because 90 knots is 1.5 nautical miles per minute and 200 × 1.5 = 300. If groundspeed increases to 120 knots, the same 200 ft/NM gradient needs about 400 feet per minute. This is why a stronger tailwind can increase the required vertical speed even though the published gradient itself has not changed.</p><h2>Gradient is not the same as climb angle</h2><p>Feet per nautical mile is a distance-based gradient. Percent grade and flight-path angle describe the same geometry in different units, but they are not interchangeable numbers. Use the units printed on the procedure or performance source and convert only when needed.</p>',
'guides/standard-rate-turn.html': '<h2>What changes with airspeed</h2><p>A standard-rate turn means roughly 3 degrees of heading change per second, so a full 360-degree turn takes about two minutes. At a higher true airspeed the airplane covers more distance each second, which means it needs more bank to keep the same turn rate. That is why a single memorized bank angle does not work at every speed.</p><h2>Rule of thumb versus exact bank</h2><p>Training shortcuts are useful for setting an initial bank angle, while the turn coordinator or other approved indication tells you whether the actual turn rate is on target. The calculator lets you compare the shortcut with the geometric result rather than treating either as an aircraft limitation.</p>',
'guides/top-of-descent.html': '<h2>Worked top-of-descent example</h2><p>If you need to lose 6,000 feet at a planned 300 ft/NM descent gradient, the geometric descent distance is about 20 NM. At 120 knots groundspeed, 20 NM takes about 10 minutes, so the corresponding average vertical speed is about 600 feet per minute. Wind, ATC restrictions, speed changes, terrain, and published procedure constraints can all change where you actually begin down.</p><h2>Use the altitude you actually need to lose</h2><p>Subtract the target altitude from the altitude where you plan to start the descent. Do not automatically use airport elevation if a crossing restriction, pattern altitude, procedure altitude, or other target applies first.</p>',
'guides/true-airspeed-rule.html': '<h2>Worked 2 percent rule example</h2><p>With 110 knots calibrated airspeed at 8,000 feet, the training shortcut adds about 16 percent: 110 × 1.16 is about 128 knots true airspeed. This is only a quick estimate. Nonstandard temperature and compressibility can make the real value different, especially as altitude and speed increase.</p><h2>CAS, TAS, and groundspeed are different</h2><p>Calibrated airspeed corrects indicated airspeed for instrument and position error. True airspeed corrects for air density. Groundspeed is the airplane&apos;s speed over the ground after wind is accounted for. Mixing those three values is a common source of bad time, wind, and turn calculations.</p>',
'guides/accelerated-stall-load-factor.html': '<h2>Worked bank-angle examples</h2><p>In a coordinated level 45° bank, load factor is about 1.41 G, so theoretical stall speed is roughly 19 percent higher than the 1-G stall speed. At 60° of bank, load factor is 2 G and theoretical stall speed is about 41 percent higher. These relationships assume a coordinated level turn and do not replace the aircraft&apos;s published limitations or maneuver guidance.</p><h2>Why the square root appears</h2><p>Stall speed changes with the square root of load factor rather than in direct proportion to G. Doubling the load factor therefore does not double stall speed. This is a useful reasonableness check when studying accelerated stalls and steep turns.</p>',
'guides/weight-and-balance.html': '<h2>Worked station example</h2><p>A 180-pound passenger sitting at an 85-inch arm contributes 15,300 lb-in of moment. Do that for the empty aircraft, fuel, passengers, and baggage, then add the weights and moments. Total moment divided by total weight gives the loaded center of gravity. The answer still has to be checked against the approved envelope for that aircraft and loading condition.</p><h2>Why both weight and CG matter</h2><p>Being under maximum gross weight does not automatically mean the loading is acceptable. A CG that is too far forward or aft can affect control forces, stability, stall behavior, rotation, flare, and recovery characteristics. Use the current aircraft weight-and-balance record and POH or AFM limits rather than a generic preset.</p>'
}
for path,extra in extras.items():
    p=Path(path)
    if not p.exists(): continue
    s=p.read_text()
    first_heading=re.search(r'<h2>(.*?)</h2>',extra)
    if first_heading and first_heading.group(1) not in s:
        anchor='<div class="pd-actions">'
        if anchor in s: s=s.replace(anchor,extra+anchor,1)
        else: s=s.replace('</main>',extra+'</main>',1)
        p.write_text(s)

# 4) Add a little more instructional context to POH Chart Studio without bloating the interface.
p=Path('poh-chart-studio.html')
if p.exists():
    s=p.read_text()
    if 'How to practice a POH chart' not in s:
        block='<section class="info-card" style="margin-top:28px"><h2>How to practice a POH chart</h2><p>Pick known chart points first, then estimate a value between them. Compare your interpolation with the plotted result and repeat with a different weight, temperature, altitude, or distance. The goal is to get comfortable reading scales, following chart lines, and spotting answers that are obviously outside the expected range.</p><h2>Use the aircraft chart for real performance</h2><p>POH charts can include notes, corrections, configuration assumptions, runway-surface factors, wind adjustments, and interpolation methods that a generic practice chart does not reproduce. PilotDesk Chart Studio is for learning the process; the current approved POH or AFM remains the source for an actual airplane.</p></section>'
        s=s.replace('</main>',block+'</main>',1)
        p.write_text(s)

# 5) Create two useful pillar pages that cover broad informational search intent without creating doorway pages.
def page_template(title,desc,h1,body,slug):
    org={'@type':'Organization','name':'PilotDesk','url':SITE+'/','logo':{'@type':'ImageObject','url':SITE+'/assets/icon.svg'}}
    article={'@context':'https://schema.org','@type':'Article','headline':h1,'description':desc,'datePublished':TODAY,'dateModified':TODAY,'mainEntityOfPage':SITE+'/'+slug,'author':org,'publisher':org}
    crumbs={'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Guides','item':SITE+'/guides.html'},{'@type':'ListItem','position':2,'name':h1,'item':SITE+'/'+slug}]}
    return f'''<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | PilotDesk</title><meta name="description" content="{desc}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#08090b"><link rel="canonical" href="{SITE}/{slug}"><link rel="stylesheet" href="/assets/styles.css"><link rel="stylesheet" href="/assets/hub.css"><link rel="icon" href="/assets/icon.svg" type="image/svg+xml"><script defer src="/assets/site.js"></script><script defer src="/assets/ad-config.js"></script><script defer src="/assets/ads.js"></script><script type="application/ld+json" data-pd-guide-schema="1">{json.dumps(article,separators=(',',':'))}</script><script type="application/ld+json" data-pd-guide-breadcrumbs="1">{json.dumps(crumbs,separators=(',',':'))}</script></head><body><header class="topbar"><a class="brand" href="/"><span class="brandmark">PD</span><span><b>PilotDesk</b><small>FLIGHT TOOLS</small></span></a><nav><a href="/">Calculators</a><a href="/airport.html">Airports</a><a href="/weather.html">Weather</a><a href="/aircraft.html">Hangar</a><a href="/guides.html">Guides</a><a href="/about.html">About</a></nav></header><main class="shell content-page"><div class="breadcrumbs"><a href="/guides.html">Guides</a> / {h1}</div><span class="badge">REFERENCE</span><h1>{h1}</h1>{body}<div class="safety-strip"><strong>Training and planning aid only.</strong> Use current approved aircraft data, regulations, weather, procedures, and operating information for an actual flight.</div></main><footer><div><b>PilotDesk</b><p>Aviation planning and training tools.</p></div><div class="footer-links"><a href="/guides.html">Guides</a><a href="/about.html">About</a><a href="/sources.html">Sources</a><a href="/legal/privacy.html">Privacy</a></div></footer></body></html>'''

formula_body='''<p>Aviation math is easier when you know what each number is trying to answer. This reference groups the formulas pilots commonly use for wind, time, fuel, altitude, climb, descent, turns, navigation, and weight and balance. Each section links to a PilotDesk calculator so you can run the math and then change the inputs to see how the result moves.</p>
<h2>Time, speed, and distance</h2><p>The basic relationship is <strong>distance = groundspeed × time</strong>. Rearranging it gives time = distance ÷ groundspeed and groundspeed = distance ÷ time. Keep the units consistent: knots are nautical miles per hour, so 120 knots covers 2 NM each minute. Use the <a href="/calculators/time-speed-distance/">time, speed, distance calculator</a> or the <a href="/calculators/nm-per-minute/">NM per minute calculator</a> for quick checks.</p>
<h2>Fuel required, endurance, and range</h2><p>Trip fuel is fuel-burn rate multiplied by trip time. Reserve fuel uses the same relationship after reserve minutes are converted to hours. Endurance is usable fuel divided by fuel burn, while still-air range is endurance multiplied by groundspeed. Real flight planning can require separate start, taxi, climb, alternate, holding, contingency, and regulatory fuel. Use <a href="/calculators/fuel-required/">fuel required</a> and <a href="/calculators/endurance-range/">endurance and range</a>, then read the <a href="/guides/fuel-planning.html">fuel planning guide</a>.</p>
<h2>Crosswind and headwind components</h2><p>If θ is the angle between the wind direction and the runway heading, crosswind is wind speed × sin(θ), and the along-runway component is wind speed × cos(θ). A negative along-runway answer represents tailwind. Keep wind and runway directions on the same true or magnetic reference. Runway headings are magnetic, tower-issued winds are magnetic, and transmitted surface observations are referenced to true north. Use the <a href="/calculators/crosswind/">crosswind component calculator</a> and the <a href="/guides/crosswind-component.html">crosswind guide</a>.</p>
<h2>Wind correction angle and groundspeed</h2><p>A wind triangle resolves the wind into cross-course and along-course components. The cross-course component determines wind correction angle; the along-course component changes groundspeed. The result connects directly to time and fuel planning, because groundspeed changes both. Use the <a href="/calculators/wind-triangle/">wind triangle calculator</a> and <a href="/guides/wind-triangle.html">wind triangle guide</a>.</p>
<h2>Pressure altitude</h2><p>A common quick estimate is field elevation + (29.92 − altimeter setting) × 1,000 feet. Lower-than-standard pressure raises pressure altitude; higher pressure lowers it. Use the <a href="/calculators/pressure-altitude/">pressure altitude calculator</a> and <a href="/guides/pressure-altitude.html">pressure altitude guide</a>.</p>
<h2>Density altitude and ISA</h2><p>Density altitude expresses the altitude in the standard atmosphere that has the same density as the current air. Temperature, pressure, and elevation all matter. PilotDesk uses an ISA atmosphere model rather than treating the classroom 120-feet-per-degree shortcut as a precision solution. Use the <a href="/calculators/density-altitude/">density altitude calculator</a>, <a href="/calculators/isa-temperature/">ISA temperature calculator</a>, and <a href="/guides/density-altitude.html">density altitude guide</a>.</p>
<h2>Climb gradient and vertical speed</h2><p>Vertical speed in feet per minute equals required climb gradient in ft/NM multiplied by groundspeed in NM/min. The reverse calculation divides vertical speed by groundspeed. Because groundspeed changes with wind, the vertical speed needed to satisfy a fixed gradient changes too. Use <a href="/calculators/climb-gradient/">climb gradient to FPM</a>, <a href="/calculators/fpm-to-gradient/">FPM to climb gradient</a>, and the <a href="/guides/climb-gradient.html">climb gradient guide</a>.</p>
<h2>Three-degree descent and top of descent</h2><p>For an exact 3° path, vertical speed is groundspeed × 6,076.1 ÷ 60 × tan(3°). The familiar mental shortcut is groundspeed × 5. Descent distance can be estimated as altitude to lose divided by the planned descent gradient. Use the <a href="/calculators/three-degree-descent/">3° descent rate calculator</a>, <a href="/calculators/top-of-descent/">top of descent calculator</a>, and the related <a href="/guides/three-degree-descent.html">descent</a> and <a href="/guides/top-of-descent.html">TOD</a> guides.</p>
<h2>Turns, load factor, and accelerated stall speed</h2><p>In a coordinated level turn, load factor is 1 ÷ cos(bank angle). The theoretical accelerated stall speed is the 1-G stall speed multiplied by the square root of load factor. Turn radius and rate also depend on true airspeed and bank angle. Use the <a href="/calculators/load-factor/">load factor</a>, <a href="/calculators/accelerated-stall/">accelerated stall</a>, <a href="/calculators/turn-radius/">turn radius</a>, <a href="/calculators/rate-of-turn/">rate of turn</a>, and <a href="/calculators/standard-rate-bank/">standard-rate bank</a> calculators.</p>
<h2>Pivotal altitude</h2><p>The common feet-and-knots training approximation is pivotal altitude AGL ≈ groundspeed² ÷ 11.3. Because groundspeed is squared, the answer changes quickly as speed changes. Use the <a href="/calculators/pivotal-altitude/">pivotal altitude calculator</a> and <a href="/guides/pivotal-altitude.html">pivotal altitude guide</a>.</p>
<h2>Weight, moment, CG, and percent MAC</h2><p>Moment is weight × arm. Loaded center of gravity is total moment ÷ total weight. Percent MAC is (CG − LEMAC) ÷ MAC length × 100. These equations do the arithmetic, but the approved aircraft envelope determines whether the loading is acceptable. Use the <a href="/calculators/moment-cg/">moment and CG calculator</a>, <a href="/calculators/percent-mac/">percent MAC calculator</a>, <a href="/calculators/ballast/">ballast calculator</a>, and <a href="/calculators/weight-balance-builder/">weight and balance builder</a>.</p>
<h2>Navigation and conversion math</h2><p>PilotDesk also covers great-circle distance, DME arc distance, reciprocal headings, true/magnetic conversion, DMS coordinates, Mach number, speed of sound, hydroplaning speed, wing loading, power loading, fuel weight, and common aviation unit conversions. Browse <a href="/">all aviation calculators</a> or use the <a href="/guides/aviation-math-glossary.html">aviation math glossary</a> when a term is unfamiliar.</p>
<h2>How to use pilot math well</h2><p>Use a formula to understand the relationship, a calculator to reduce arithmetic errors, and the current approved source to make an operational decision. A result should also pass a reasonableness check. If a 20-knot wind at 30° produces a 30-knot crosswind, or 120 knots somehow covers 10 NM per minute, stop and check the units before doing anything with the answer.</p>'''
Path('guides/pilot-math-formulas.html').write_text(page_template('Pilot Math Formulas & Aviation Calculator Reference','A pilot math formula reference for wind, flight planning, altitude, climb, descent, turns, navigation, fuel, and aircraft weight and balance.','Pilot Math Formulas and Aviation Calculation Reference',formula_body,'guides/pilot-math-formulas.html'))

glossary_body='''<p>This glossary explains the terms that appear across PilotDesk calculators and flight-planning tools. It is written for quick lookup: what the term means, which units are normally used, and which calculation it connects to.</p>
<h2>Airspeed terms</h2><p><strong>IAS — indicated airspeed:</strong> the value shown on the airspeed indicator before correcting for instrument and position error. <strong>CAS — calibrated airspeed:</strong> IAS corrected for those errors. <strong>TAS — true airspeed:</strong> the airplane&apos;s speed through the air mass after accounting for air density. <strong>Groundspeed:</strong> speed across the ground after wind is included. Groundspeed drives time, descent-rate, and climb-gradient calculations. See the <a href="/calculators/true-airspeed/">TAS estimate</a> and <a href="/calculators/time-speed-distance/">time/speed/distance calculator</a>.</p>
<h2>Wind and navigation terms</h2><p><strong>Wind correction angle (WCA):</strong> the heading correction used to counter crosswind and maintain a desired course. <strong>Headwind component:</strong> the portion of wind opposing travel along the runway or course. <strong>Tailwind component:</strong> the portion pushing in the direction of travel. <strong>Crosswind component:</strong> the portion acting perpendicular to the runway or course. <strong>True direction</strong> is referenced to true north, while <strong>magnetic direction</strong> is referenced to magnetic north. See the <a href="/calculators/wind-triangle/">wind triangle</a>, <a href="/calculators/crosswind/">crosswind</a>, and <a href="/calculators/true-magnetic/">true/magnetic</a> tools.</p>
<h2>Altitude and atmosphere terms</h2><p><strong>Pressure altitude:</strong> altitude referenced to the standard pressure datum of 29.92 inHg. <strong>Density altitude:</strong> the standard-atmosphere altitude corresponding to the current air density. <strong>ISA:</strong> International Standard Atmosphere, the reference model used for standard pressure and temperature relationships. <strong>OAT:</strong> outside air temperature. <strong>Dew point:</strong> the temperature at which air becomes saturated if cooled at constant pressure. See the <a href="/calculators/pressure-altitude/">pressure altitude</a>, <a href="/calculators/density-altitude/">density altitude</a>, <a href="/calculators/isa-temperature/">ISA temperature</a>, and <a href="/calculators/cloud-base/">estimated cloud base</a> tools.</p>
<h2>Climb and descent terms</h2><p><strong>FPM:</strong> feet per minute, a vertical-speed unit. <strong>ft/NM:</strong> feet gained or lost for each nautical mile traveled over the ground. <strong>Climb gradient:</strong> vertical gain per horizontal distance. <strong>Flight-path angle:</strong> the geometric angle between the flight path and the horizontal. <strong>Top of descent (TOD):</strong> a planning point where descent begins to meet a target altitude, gradient, or path. See <a href="/calculators/climb-gradient/">climb gradient</a>, <a href="/calculators/gradient-angle/">gradient/angle</a>, <a href="/calculators/three-degree-descent/">3° descent</a>, and <a href="/calculators/top-of-descent/">TOD</a>.</p>
<h2>Turn and maneuver terms</h2><p><strong>Load factor:</strong> lift divided by aircraft weight, commonly expressed in G. <strong>Standard-rate turn:</strong> approximately 3° of heading change per second. <strong>Turn radius:</strong> horizontal radius of the flight path in a coordinated turn. <strong>Rate of turn:</strong> heading change per unit time. <strong>Pivotal altitude:</strong> the altitude at which a visual reference appears stationary relative to a lateral axis during pivotal maneuvers; the common training estimate depends on groundspeed squared. See the <a href="/calculators/load-factor/">load factor</a>, <a href="/calculators/standard-rate-bank/">standard-rate bank</a>, <a href="/calculators/turn-radius/">turn radius</a>, and <a href="/calculators/pivotal-altitude/">pivotal altitude</a> calculators.</p>
<h2>Stall and performance terms</h2><p><strong>1-G stall speed:</strong> stall speed at a load factor of one. <strong>Accelerated stall:</strong> a stall occurring at a load factor greater than one, so stall speed is higher than the 1-G value. <strong>Wing loading:</strong> aircraft weight divided by wing area. <strong>Power loading:</strong> aircraft weight divided by engine horsepower. <strong>Dynamic hydroplaning speed:</strong> a rule-of-thumb estimate related to tire pressure, not a guarantee of when hydroplaning will begin or end. See the <a href="/calculators/accelerated-stall/">accelerated stall</a>, <a href="/calculators/wing-loading/">wing loading</a>, <a href="/calculators/power-loading/">power loading</a>, and <a href="/calculators/hydroplaning/">hydroplaning</a> tools.</p>
<h2>Weight and balance terms</h2><p><strong>Arm:</strong> horizontal distance from the aircraft datum to a station. <strong>Moment:</strong> weight multiplied by arm. <strong>Center of gravity (CG):</strong> the balance point represented by total moment divided by total weight. <strong>MAC:</strong> mean aerodynamic chord. <strong>LEMAC:</strong> leading edge of the mean aerodynamic chord. <strong>Percent MAC:</strong> CG position expressed as a percentage of MAC. <strong>Ballast:</strong> weight intentionally added at a known arm to move CG. See the <a href="/calculators/weight-balance-builder/">weight and balance builder</a>, <a href="/calculators/moment-cg/">moment/CG</a>, <a href="/calculators/percent-mac/">percent MAC</a>, and <a href="/calculators/ballast/">ballast</a> tools.</p>
<h2>Distance and coordinate terms</h2><p><strong>Nautical mile (NM):</strong> the standard aviation distance unit, equal to 1,852 meters. <strong>DME arc:</strong> a curved path flown at an approximately constant DME distance from a station. <strong>Great-circle distance:</strong> the shortest path between two points on a sphere. <strong>DMS:</strong> degrees, minutes, and seconds for geographic coordinates. See <a href="/calculators/arc-distance/">DME arc distance</a>, <a href="/calculators/great-circle-distance/">great-circle distance</a>, and <a href="/calculators/dms-decimal/">DMS/decimal conversion</a>.</p>
<h2>Mach and atmospheric speed terms</h2><p><strong>Mach number:</strong> true airspeed divided by the local speed of sound. <strong>Speed of sound:</strong> the propagation speed of small pressure disturbances through air; temperature is a major input. See the <a href="/calculators/mach-number/">Mach number</a> and <a href="/calculators/speed-of-sound/">speed of sound</a> calculators.</p>
<h2>Common aviation units</h2><p>PilotDesk includes conversions for knots, mph, km/h, nautical miles, statute miles, kilometers, pounds, kilograms, U.S. gallons, liters, inHg, hPa, Celsius, Fahrenheit, feet per minute, and meters per second. Use the conversion only after confirming the source unit; the arithmetic can be correct while the answer is wrong if the starting unit was misidentified. Browse the <a href="/">calculator list</a> or the <a href="/guides/pilot-math-formulas.html">pilot math formula reference</a>.</p>'''
Path('guides/aviation-math-glossary.html').write_text(page_template('Aviation Math Glossary for Pilots','Definitions for common pilot math and aviation calculation terms including TAS, groundspeed, WCA, pressure altitude, density altitude, CG, MAC, climb gradient, and load factor.','Aviation Math Glossary for Pilots',glossary_body,'guides/aviation-math-glossary.html'))

# 6) Add pillar pages to the guide hub.
p=Path('guides.html'); s=p.read_text()
if '/guides/pilot-math-formulas.html' not in s:
    cards='<div class="pd-hub-grid" style="margin:20px 0"><a class="pd-hub-card wide" href="/guides/pilot-math-formulas.html"><small>Pilot math</small><h2>Pilot Math Formula Reference</h2><p>Wind, time, fuel, altitude, climb, descent, turns, navigation, and weight-and-balance formulas with calculator links.</p><span class="pd-arrow">Open reference →</span></a><a class="pd-hub-card wide" href="/guides/aviation-math-glossary.html"><small>Reference</small><h2>Aviation Math Glossary</h2><p>Plain-English definitions for TAS, groundspeed, WCA, pressure altitude, density altitude, CG, MAC, gradients, and more.</p><span class="pd-arrow">Open glossary →</span></a></div>'
    s=s.replace('<div class="pd-hub-grid" style="margin:20px 0">',cards+'<div class="pd-hub-grid" style="margin:20px 0">',1)
p.write_text(s)

# 7) Normalize Article + breadcrumb structured data across all guide pages.
for p in sorted(Path('guides').glob('*.html')):
    ensure_guide_schema(str(p))

# 8) Permanent canonical-only sitemap generator.
Path('scripts/generate-sitemap.mjs').write_text(r'''import fs from 'node:fs';
import path from 'node:path';
const SITE='https://www.pilot-desk.com';
const skipDirs=new Set(['.git','node_modules','.github','api','assets','qa','scripts']);
const files=[];
function walk(dir='.') { for(const ent of fs.readdirSync(dir,{withFileTypes:true})) { if(skipDirs.has(ent.name)) continue; const p=path.join(dir,ent.name); if(ent.isDirectory()) walk(p); else if(ent.isFile()&&ent.name.endsWith('.html')&&ent.name!=='404.html') files.push(p.replaceAll('\\','/').replace(/^\.\//,'')); } }
walk();
function publicUrl(file){ if(file==='index.html') return SITE+'/'; if(file.endsWith('/index.html')) return SITE+'/'+file.slice(0,-'index.html'.length); return SITE+'/'+file; }
const urls=[];
for(const file of files){ const html=fs.readFileSync(file,'utf8'); if(/<meta[^>]+name=["']robots["'][^>]+content=["'][^"']*noindex/i.test(html)||/<meta[^>]+content=["'][^"']*noindex[^"']*["'][^>]+name=["']robots["']/i.test(html)) continue; const m=html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)||html.match(/<link[^>]+href=["']([^"']+)["'][^>]+rel=["']canonical["']/i); if(!m) continue; const canonical=m[1].replace('https://pilot-desk.com',SITE); if(!canonical.startsWith(SITE+'/')) continue; const expected=publicUrl(file); if(canonical.replace(/\/$/,'')!==expected.replace(/\/$/,'')) continue; urls.push(canonical); }
const unique=[...new Set(urls)].sort((a,b)=>a===SITE+'/'?-1:b===SITE+'/'?1:a.localeCompare(b));
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const xml=['<?xml version="1.0" encoding="UTF-8"?>','<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',...unique.map(u=>`<url><loc>${esc(u)}</loc></url>`),'</urlset>',''].join('\n');
fs.writeFileSync('sitemap.xml',xml);
console.log(`Generated canonical sitemap with ${unique.length} URLs.`);
''')

# 9) Permanent SEO regression QA.
Path('qa/seo-hardening.mjs').write_text(r'''import fs from 'node:fs';
import path from 'node:path';
let errors=[];
const fail=x=>errors.push(x);
const calcDirs=fs.readdirSync('calculators',{withFileTypes:true}).filter(x=>x.isDirectory());
for(const d of calcDirs){ const file=`calculators/${d.name}/index.html`; if(!fs.existsSync(file)) continue; const h=fs.readFileSync(file,'utf8'); if(!h.includes('data-pd-static-calc-schema')) fail(`${file}: missing static app schema`); if(!h.includes('"offers":{"@type":"Offer","price":"0","priceCurrency":"USD"}')) fail(`${file}: free app Offer schema missing`); if(!h.includes('data-pd-static-breadcrumbs')) fail(`${file}: breadcrumb schema missing`); if(!h.includes('Pilot math formula reference')) fail(`${file}: semantic internal link block missing`); }
for(const ent of fs.readdirSync('guides',{withFileTypes:true}).filter(x=>x.isFile()&&x.name.endsWith('.html'))){ const file=`guides/${ent.name}`,h=fs.readFileSync(file,'utf8'); if(!h.includes('data-pd-guide-schema')) fail(`${file}: Article schema missing`); if(!h.includes('data-pd-guide-breadcrumbs')) fail(`${file}: breadcrumb schema missing`); }
for(const file of ['guides/pilot-math-formulas.html','guides/aviation-math-glossary.html']){ const h=fs.readFileSync(file,'utf8'); const words=h.replace(/<[^>]+>/g,' ').split(/\s+/).filter(Boolean).length; if(words<700) fail(`${file}: pillar content too short (${words} words)`); }
const map=new Map();
function walk(dir='.') { for(const ent of fs.readdirSync(dir,{withFileTypes:true})) { if(['.git','node_modules','.github','api','assets','qa','scripts'].includes(ent.name)) continue; const p=path.join(dir,ent.name); if(ent.isDirectory()) walk(p); else if(ent.isFile()&&ent.name.endsWith('.html')&&ent.name!=='404.html'){ const f=p.replaceAll('\\','/').replace(/^\.\//,''),h=fs.readFileSync(p,'utf8'); const m=h.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)||h.match(/<link[^>]+href=["']([^"']+)["'][^>]+rel=["']canonical["']/i); if(m) map.set(m[1].replace('https://pilot-desk.com','https://www.pilot-desk.com'),{f,h}); }} }
walk();
const sitemap=fs.readFileSync('sitemap.xml','utf8'); const locs=[...sitemap.matchAll(/<loc>(.*?)<\/loc>/g)].map(x=>x[1].replaceAll('&amp;','&')); for(const u of locs){ const entry=map.get(u); if(!entry) fail(`sitemap URL missing self-canonical HTML: ${u}`); else if(/noindex/i.test((entry.h.match(/<meta[^>]+name=["']robots["'][^>]*>/i)||[''])[0])) fail(`sitemap contains noindex page: ${u}`); }
if(sitemap.includes('weight-balance.html</loc>')) fail('canonicalized weight-balance.html must not be in sitemap');
if(fs.readFileSync('assets/seo.js','utf8').includes('SearchAction')) fail('fake homepage SearchAction should not be emitted');
if(errors.length){ console.error(errors.join('\n')); process.exit(1); }
console.log(`SEO hardening PASS: ${calcDirs.length} calculator dirs, ${locs.length} sitemap URLs, guide schemas, pillar content, and app offers checked.`);
''')

# 10) Add hardening QA and sitemap generation to permanent workflows.
p=Path('.github/workflows/qa.yml'); s=p.read_text()
if 'Run SEO hardening checks' not in s:
    s=s.replace('      - name: Check Google audit regressions\n        run: node qa/google-audit.mjs\n','      - name: Check Google audit regressions\n        run: node qa/google-audit.mjs\n      - name: Run SEO hardening checks\n        run: node qa/seo-hardening.mjs\n')
p.write_text(s)
p=Path('.github/workflows/generate-calculators.yml'); s=p.read_text()
if 'Generate canonical sitemap' not in s:
    s=s.replace('      - name: Apply static branding and aviation FAQ content\n        run: node scripts/postprocess-site.mjs\n','      - name: Apply static branding and aviation FAQ content\n        run: node scripts/postprocess-site.mjs\n      - name: Generate canonical sitemap\n        run: node scripts/generate-sitemap.mjs\n')
p.write_text(s)

# 11) Lightweight llms.txt for AI discovery. This is not a Google ranking trick.
Path('llms.txt').write_text('''# PilotDesk\n\nPilotDesk provides free browser-based aviation calculators, pilot math references, airport weather tools, flight-planning tools, aircraft profiles, and training aids.\n\n## Primary pages\n- https://www.pilot-desk.com/ — aviation calculators\n- https://www.pilot-desk.com/planner.html — pilot flight planner\n- https://www.pilot-desk.com/weather.html — aviation weather, METAR and TAF\n- https://www.pilot-desk.com/metar-decoder.html — METAR decoder\n- https://www.pilot-desk.com/airport.html — airport search and FAA procedure links\n- https://www.pilot-desk.com/guides.html — aviation guides\n- https://www.pilot-desk.com/guides/pilot-math-formulas.html — pilot math formula reference\n- https://www.pilot-desk.com/guides/aviation-math-glossary.html — aviation math glossary\n- https://www.pilot-desk.com/sources.html — sources and methods\n\n## Notes\nPilotDesk is a supplemental planning and training aid. Operational decisions should be verified against current approved aircraft data, official weather, regulations, procedures, NOTAMs, and other applicable authoritative sources.\n''')

print('Maximum safe SEO pass applied.')
