import "jsr:@supabase/functions-js/edge-runtime.d.ts";
type Question={id:string;prompt:string;options:string[];correct:number;explanation:string};
type Challenge={key:string;title:string;category:string;difficulty:string;deck:string;questions:Question[]};
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const json=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers:cors});
const challenges:Challenge[]=[
 {key:"metar-visibility-wind",title:"METAR Decode",category:"Weather",difficulty:"Starter",deck:"Read the report, then make three quick interpretations.",questions:[
  {id:"wind",prompt:"METAR: KDEN 141653Z 18018G27KT 10SM FEW080 24/08 A3008. What is the reported wind?",options:["180° at 18 kt, gusting 27 kt","180° at 27 kt, gusting 18 kt","018° at 27 kt","Variable at 18 kt"],correct:0,explanation:"18018G27KT means wind from 180 degrees at 18 knots with gusts to 27 knots."},
  {id:"vis",prompt:"What visibility is reported in that METAR?",options:["1 statute mile","8 statute miles","10 statute miles","Unlimited"],correct:2,explanation:"10SM reports 10 statute miles of prevailing visibility."},
  {id:"temp",prompt:"What are the temperature and dew point?",options:["24°C / 8°C","8°C / 24°C","24°F / 8°F","30°C / 8°C"],correct:0,explanation:"The temperature/dew point group 24/08 is 24°C and 8°C."}
 ]},
 {key:"metar-ceiling-altimeter",title:"Ceiling Check",category:"Weather",difficulty:"Starter",deck:"Separate cloud coverage from an actual ceiling.",questions:[
  {id:"ceil",prompt:"METAR: KBIS 141852Z 32012KT 6SM -RA BKN018 OVC035 12/10 A2986. What is the ceiling?",options:["1,800 ft AGL","3,500 ft AGL","6,000 ft AGL","No ceiling is reported"],correct:0,explanation:"A ceiling is the lowest broken, overcast, or vertical-visibility layer. BKN018 is 1,800 ft AGL."},
  {id:"wx",prompt:"What weather is being reported?",options:["Heavy rain","Light rain","Rain showers","Mist"],correct:1,explanation:"-RA means light rain."},
  {id:"alt",prompt:"What altimeter setting is reported?",options:["29.68 inHg","29.86 inHg","30.86 inHg","2,986 hPa"],correct:1,explanation:"A2986 means 29.86 inches of mercury."}
 ]},
 {key:"metar-variable-wind",title:"Wind Group",category:"Weather",difficulty:"Starter",deck:"Decode a variable-wind report without overthinking it.",questions:[
  {id:"var",prompt:"METAR: KMSP 141753Z VRB05KT 10SM SCT050 21/09 A3012. What does VRB05KT mean?",options:["Wind variable at 5 kt","Wind from 005° at 5 kt","Wind variable gusting 5 kt","Calm wind"],correct:0,explanation:"VRB indicates variable direction; 05KT is 5 knots."},
  {id:"cloud",prompt:"Does SCT050 constitute a ceiling?",options:["Yes, at 500 ft","Yes, at 5,000 ft","No","Only at night"],correct:2,explanation:"Scattered clouds are not a ceiling. Broken, overcast, and vertical visibility define ceilings."},
  {id:"alt",prompt:"A3012 corresponds to what altimeter setting?",options:["30.12 inHg","30.21 inHg","29.12 inHg","301.2 inHg"],correct:0,explanation:"A3012 decodes to 30.12 inHg."}
 ]},
 {key:"taf-timing",title:"TAF Timing",category:"Weather",difficulty:"Intermediate",deck:"Use the forecast groups in order and identify when a change applies.",questions:[
  {id:"fm",prompt:"In a TAF, what does FM1800 indicate?",options:["Conditions become prevailing from 1800Z onward","Conditions last for exactly 18 hours","A temporary change begins at 1800 local","Forecast was issued at 1800Z"],correct:0,explanation:"FM means 'from'; the new conditions become prevailing starting at the stated Zulu time."},
  {id:"tempo",prompt:"What does TEMPO normally describe?",options:["A permanent change","Temporary fluctuations expected during the stated period","Only wind changes","An observation, not a forecast"],correct:1,explanation:"TEMPO describes temporary fluctuations expected during the stated period."},
  {id:"zulu",prompt:"TAF times are normally expressed in which time standard?",options:["Local standard time","Local daylight time","UTC/Zulu","Airport tower time"],correct:2,explanation:"TAF issue and forecast times use UTC, commonly called Zulu time."}
 ]},
 {key:"performance-density-altitude",title:"Performance Sense Check",category:"Performance",difficulty:"Intermediate",deck:"Reason through density altitude before reaching for a calculator.",questions:[
  {id:"hot",prompt:"All else equal, what does a hotter-than-standard day do to density altitude?",options:["Raises it","Lowers it","Does not change it","Makes it equal pressure altitude"],correct:0,explanation:"Higher temperature lowers air density, which raises density altitude."},
  {id:"perf",prompt:"As density altitude increases, typical normally aspirated aircraft takeoff performance generally does what?",options:["Improves","Degrades","Stays identical","Only changes above 10,000 ft"],correct:1,explanation:"Higher density altitude generally means reduced engine/propeller/wing performance and longer takeoff distance."},
  {id:"humid",prompt:"Compared with dry air at the same pressure and temperature, very humid air is generally...",options:["Slightly less dense","Much more dense","Exactly the same density","Impossible to compare"],correct:0,explanation:"Water vapor is lighter than the nitrogen/oxygen mixture it displaces, so humid air is slightly less dense."}
 ]},
 {key:"crosswind-components",title:"Crosswind Reasoning",category:"Performance",difficulty:"Intermediate",deck:"Think in components instead of treating the full wind as crosswind.",questions:[
  {id:"headon",prompt:"A 20 kt wind is exactly aligned with the runway centerline as a headwind. Approximate crosswind component?",options:["0 kt","10 kt","20 kt","28 kt"],correct:0,explanation:"With zero angular difference from the runway, the crosswind component is zero."},
  {id:"ninety",prompt:"A 16 kt wind is exactly 90° to the runway. Approximate crosswind component?",options:["0 kt","8 kt","11 kt","16 kt"],correct:3,explanation:"At 90 degrees, essentially the entire wind speed is crosswind component."},
  {id:"gust",prompt:"For a gusty crosswind, which value deserves specific attention when comparing conditions with aircraft/pilot limits?",options:["Only the steady wind direction","The gust component as well as the steady wind","Only temperature","Only altimeter setting"],correct:1,explanation:"Gusts can materially increase the instantaneous crosswind component and handling demand."}
 ]},
 {key:"adm-go-no-go",title:"ADM Scenario",category:"Decision Making",difficulty:"Intermediate",deck:"Choose the answer that best preserves options and margins.",questions:[
  {id:"pressure",prompt:"You are running late and weather is trending worse near your destination. Which response best reflects good aeronautical decision making?",options:["Continue because schedule pressure is not a flight risk","Reassess the plan, margins, alternates, and willingness to delay or divert","Increase airspeed to make up time","Ignore the trend until reaching the destination area"],correct:1,explanation:"Good ADM recognizes external pressure and deliberately reevaluates margins and alternatives."},
  {id:"out",prompt:"Why is identifying an 'out' before conditions deteriorate useful?",options:["It guarantees the flight will be legal","It preserves a preplanned alternative before workload and pressure rise","It removes the need for weather updates","It allows exceeding aircraft limitations"],correct:1,explanation:"A preplanned out reduces decision friction when workload or pressure increases."},
  {id:"bias",prompt:"Continuing mainly because you have already invested time and fuel in the trip is closest to which decision trap?",options:["Sunk-cost thinking","Proper risk management","Checklist discipline","Crew resource management"],correct:0,explanation:"Past investment should not justify accepting new risk; that is classic sunk-cost thinking."}
 ]},
 {key:"stabilized-approach",title:"Approach Discipline",category:"Decision Making",difficulty:"Intermediate",deck:"Focus on energy, configuration, and a clear go-around decision.",questions:[
  {id:"unstable",prompt:"If an approach does not meet your stabilized-approach criteria by the required gate, the normal response should be to...",options:["Continue and fix it close to the runway","Go around","Add more flap regardless of limitations","Turn off alerts"],correct:1,explanation:"A go-around is the normal response when the approach is outside established stabilized criteria at the gate."},
  {id:"energy",prompt:"Why does excessive speed on final matter?",options:["It can increase landing distance and make the approach harder to stabilize","It always shortens landing distance","It has no effect once flaps are extended","It only matters in jets"],correct:0,explanation:"Extra kinetic energy generally increases landing distance and can complicate stabilization."},
  {id:"goaround",prompt:"A go-around is best thought of as...",options:["A failed landing","A normal maneuver used when landing conditions are not satisfactory","An emergency-only maneuver","A maneuver prohibited after reaching final"],correct:1,explanation:"A go-around is a normal, trained maneuver and a key risk-control option."}
 ]},
 {key:"pitot-static",title:"Pitot-Static Basics",category:"Systems",difficulty:"Intermediate",deck:"Match each source to the instrument information it supports.",questions:[
  {id:"pitot",prompt:"Which primary flight instrument directly uses pitot pressure?",options:["Airspeed indicator","Altimeter","Vertical speed indicator","Magnetic compass"],correct:0,explanation:"The airspeed indicator compares pitot (total) pressure with static pressure."},
  {id:"static",prompt:"Which pair both rely on static pressure?",options:["Altimeter and VSI","Tachometer and compass","Turn coordinator and tachometer","Oil pressure and ammeter"],correct:0,explanation:"The altimeter and VSI both use static-system pressure."},
  {id:"blocked",prompt:"A blocked static source can affect which group of instruments?",options:["Airspeed indicator, altimeter, and VSI","Only the compass","Only engine RPM","Only fuel quantity"],correct:0,explanation:"The airspeed indicator, altimeter, and VSI all depend on the static system."}
 ]},
 {key:"weight-balance",title:"Weight & Balance",category:"Performance",difficulty:"Intermediate",deck:"Reason about center of gravity before doing the arithmetic.",questions:[
  {id:"aft",prompt:"Moving a load aft, with total weight unchanged, generally moves the CG...",options:["Forward","Aft","Nowhere","Directly to the datum"],correct:1,explanation:"Moving weight aft increases its moment arm and shifts the aircraft CG aft."},
  {id:"moment",prompt:"Basic moment is calculated as...",options:["Weight × arm","Weight ÷ arm","Arm ÷ weight","Weight + arm"],correct:0,explanation:"Moment equals weight multiplied by its arm from the datum."},
  {id:"limits",prompt:"Why must both weight and CG limits be checked?",options:["Because being under max weight alone does not guarantee the CG is within limits","Because CG never changes with loading","Because only CG matters","Because only takeoff weight matters"],correct:0,explanation:"An aircraft can be below maximum weight and still be loaded outside its allowable CG envelope."}
 ]},
 {key:"icing-awareness",title:"Icing Awareness",category:"Weather",difficulty:"Intermediate",deck:"Recognize the ingredients and protect margin early.",questions:[
  {id:"ingredients",prompt:"Structural icing risk generally requires visible moisture plus...",options:["Temperatures conducive to freezing","A tailwind","High pressure only","A dry cloudless layer"],correct:0,explanation:"Visible moisture and sufficiently cold temperatures are the core ingredients for airframe icing."},
  {id:"effect",prompt:"Ice accumulation on an airfoil can...",options:["Increase drag and reduce lift","Always improve stall margin","Only affect appearance","Eliminate induced drag"],correct:0,explanation:"Ice can disrupt airflow, increasing drag and reducing lift while degrading stall characteristics."},
  {id:"strategy",prompt:"The strongest planning response to forecast icing beyond aircraft/pilot capability is generally to...",options:["Plan to avoid the icing environment","Assume forecasts are conservative and continue","Rely on higher airspeed","Wait until accumulation is severe before changing plans"],correct:0,explanation:"Avoidance is the primary strategy when forecast conditions exceed aircraft or pilot capability."}
 ]},
 {key:"runway-signs",title:"Airport Surface",category:"Airport Ops",difficulty:"Starter",deck:"Keep runway awareness simple and deliberate.",questions:[
  {id:"hold",prompt:"Before crossing an assigned runway hold-short line, a pilot should have...",options:["An explicit clearance when operating at a towered airport","Only a taxi clearance to the ramp","A passenger's approval","The landing light off"],correct:0,explanation:"At a towered airport, crossing a runway requires the appropriate explicit ATC clearance."},
  {id:"verify",prompt:"A good defense against a runway incursion is to...",options:["Verify signs/markings and mentally trace the taxi route before moving","Taxi faster to reduce time on the surface","Avoid using the airport diagram","Rely only on memory"],correct:0,explanation:"Deliberate route review and continuous sign/marking verification reduce navigation errors on the surface."},
  {id:"uncertain",prompt:"If unsure of your position while taxiing, the best immediate action is to...",options:["Stop in a safe place and clarify","Keep moving until something looks familiar","Enter the nearest runway","Accelerate to clear the area"],correct:0,explanation:"Stopping safely and clarifying position prevents uncertainty from becoming an incursion."}
 ]}
];
const utcDate=()=>new Date().toISOString().slice(0,10);const dayIndex=(date:string)=>Math.floor(Date.parse(`${date}T00:00:00Z`)/86400000);const challengeFor=(date:string)=>challenges[((dayIndex(date)%challenges.length)+challenges.length)%challenges.length];const publicChallenge=(c:Challenge)=>({...c,questions:c.questions.map(({correct,explanation,...q})=>q)});const reviewFor=(c:Challenge,answers:number[])=>c.questions.map((q,i)=>({id:q.id,selected:Number.isInteger(answers[i])?answers[i]:null,correctIndex:q.correct,correct:answers[i]===q.correct,explanation:q.explanation}));
Deno.serve(async(req:Request)=>{
 if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(!["GET","POST"].includes(req.method))return json(405,{error:"Method not allowed"});
 const base=(Deno.env.get("SUPABASE_URL")||"").replace(/\/+$/,'');const anon=Deno.env.get("SUPABASE_ANON_KEY")||"";const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!base||!anon||!service)return json(503,{error:"PilotDesk Daily is not configured."});
 const date=utcDate(),challenge=challengeFor(date),adminHeaders={apikey:service,Authorization:`Bearer ${service}`};const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,'').trim();let user:any=null;
 if(token){const ur=await fetch(`${base}/auth/v1/user`,{headers:{apikey:anon,Authorization:`Bearer ${token}`}});if(ur.ok)user=await ur.json()}
 const countToday=async()=>{const r=await fetch(`${base}/rest/v1/daily_progress?select=id&challenge_date=eq.${date}&challenge_type=eq.pilot_daily`,{method:"HEAD",headers:{...adminHeaders,Prefer:"count=exact"}});const m=String(r.headers.get("content-range")||"").match(/\/(\d+)$/);return m?Number(m[1]):0};
 try{
  if(req.method==="GET"){
   let completion:any=null,badges:string[]=[];if(user?.id){const r=await fetch(`${base}/rest/v1/daily_progress?select=score,max_score,xp_awarded,perfect,completed_at,challenge_key&user_id=eq.${encodeURIComponent(user.id)}&challenge_date=eq.${date}&challenge_type=eq.pilot_daily&limit=1`,{headers:adminHeaders});if(r.ok){const rows=await r.json();completion=Array.isArray(rows)?rows[0]||null:null}const br=await fetch(`${base}/rest/v1/user_badges?select=badge_key&user_id=eq.${encodeURIComponent(user.id)}&order=earned_at.desc&limit=12`,{headers:adminHeaders});if(br.ok){const rows=await br.json();badges=Array.isArray(rows)?rows.map((x:any)=>x.badge_key):[]}}
   const attemptsToday=await countToday();const body:any={date,challenge:publicChallenge(challenge),attemptsToday,authenticated:Boolean(user?.id),completion,badges};if(completion)body.review=reviewFor(challenge,challenge.questions.map(q=>q.correct));return json(200,body)
  }
  const body=await req.json().catch(()=>({}));const answers=Array.isArray(body?.answers)?body.answers.map((x:any)=>Number(x)):[];if(answers.length!==challenge.questions.length||answers.some((x:number)=>!Number.isInteger(x)||x<0||x>3))return json(400,{error:"Submit one answer for each question."});const review=reviewFor(challenge,answers);const score=review.filter(x=>x.correct).length,maxScore=challenge.questions.length;
  if(!user?.id)return json(200,{date,challengeKey:challenge.key,score,maxScore,perfect:score===maxScore,saved:false,review,message:"Create a free PilotDesk account to save XP and start a streak."});
  const rpc=await fetch(`${base}/rest/v1/rpc/complete_pilot_daily`,{method:"POST",headers:{...adminHeaders,"Content-Type":"application/json"},body:JSON.stringify({p_user_id:user.id,p_challenge_date:date,p_challenge_key:challenge.key,p_score:score,p_max_score:maxScore})});if(!rpc.ok)throw new Error(`completion ${rpc.status}: ${(await rpc.text()).slice(0,300)}`);const result=await rpc.json();return json(200,{date,challengeKey:challenge.key,saved:true,review,...result});
 }catch(error){console.error("pilot-daily",error);return json(500,{error:"Unable to complete today's challenge right now."})}
});
