export type Track='ppl'|'ira'|'cpl'|'cfi'|'cfii'|'atp';
export type PrepQuestion={id:string;area:string;prompt:string;options:string[];correct:number;explanation:string;reference:string;source:'faa-sample-derived'|'pilotdesk-faa-aligned';sourceUrl?:string};
export type TrackMeta={label:string;testCode:string;officialQuestions:number;officialMinutes:number;passingScore:number;description:string};

const FAA_TESTING='https://www.faa.gov/training_testing/testing';
const FAA_ACS='https://www.faa.gov/training_testing/testing/acs';
const FAA_PILOT_HANDBOOKS='https://www.faa.gov/regulations_policies/handbooks_manuals/aviation';
const PAR='https://www.faa.gov/sites/faa.gov/files/training_testing/testing/test_questions/par_questions.pdf';
const CAX='https://www.faa.gov/sites/faa.gov/files/training_testing/testing/test_questions/cax_questions.pdf';
const FIA='https://www.faa.gov/sites/faa.gov/files/training_testing/testing/test_questions/fia_questions.pdf';
const IRA='https://www.faa.gov/training_testing/testing/test_questions';
const ATM='https://www.faa.gov/training_testing/testing/test_questions';

export const trackMeta:Record<Track,TrackMeta>={
 ppl:{label:'Private Pilot Airplane',testCode:'PAR',officialQuestions:60,officialMinutes:120,passingScore:70,description:'Private pilot regulations, weather, navigation, performance, systems, airport operations, and ADM.'},
 ira:{label:'Instrument Rating Airplane',testCode:'IRA',officialQuestions:60,officialMinutes:120,passingScore:70,description:'IFR regulations, weather, instruments, navigation, clearances, holding, and approaches.'},
 cpl:{label:'Commercial Pilot Airplane',testCode:'CAX',officialQuestions:100,officialMinutes:150,passingScore:70,description:'Commercial privileges, operations, performance, aerodynamics, weather, systems, and advanced planning.'},
 cfi:{label:'Flight Instructor Airplane',testCode:'FIA',officialQuestions:100,officialMinutes:150,passingScore:70,description:'Instructor responsibilities, teaching and learning, endorsements, aerodynamics, maneuvers, and risk management.'},
 cfii:{label:'Flight Instructor Instrument Airplane',testCode:'FII',officialQuestions:50,officialMinutes:150,passingScore:70,description:'Instrument instruction, IFR regulations, systems, weather, procedures, approaches, and common student errors.'},
 atp:{label:'Airline Transport Pilot Multiengine',testCode:'ATM',officialQuestions:125,officialMinutes:210,passingScore:70,description:'Air-carrier regulations, turbine systems, high-altitude aerodynamics, IFR operations, weather, and CRM.'}
};

const q=(id:string,area:string,prompt:string,options:string[],correct:number,explanation:string,reference:string,source:'faa-sample-derived'|'pilotdesk-faa-aligned'='pilotdesk-faa-aligned',sourceUrl?:string):PrepQuestion=>({id,area,prompt,options,correct,explanation,reference,source,sourceUrl});

export const banks:Record<Track,PrepQuestion[]>={
 ppl:[
  q('ppl-category','Regulations & Airspace','Which list contains aircraft categories rather than airplane classes?',['Airplane, rotorcraft, glider, lighter-than-air','Single-engine land, multiengine land, single-engine sea','Tailwheel, complex, high-performance, turbine'],0,'Airplane, rotorcraft, glider, and lighter-than-air are aircraft categories. Single-engine land and multiengine land are classes within the airplane category.','14 CFR 1.1 / FAA PAR sample','faa-sample-derived',PAR),
  q('ppl-class-b','Regulations & Airspace','ATC replies to your Class B entry request with your callsign and “standby.” May you enter the Class B airspace?',['Yes, because ATC used your callsign','No, remain outside until ATC explicitly clears you into Class B','Yes, if your transponder is operating'],1,'Class B requires an explicit ATC clearance. Acknowledgment or “standby” is not a Class B clearance.','14 CFR 91.131'),
  q('ppl-classg-day','Regulations & Airspace','During daytime VFR in Class G airspace more than 1,200 feet AGL but below 10,000 feet MSL, what minimum flight visibility applies?',['1 statute mile','3 statute miles','5 statute miles'],0,'Day VFR in this Class G altitude band requires 1 statute mile flight visibility. Verify current 14 CFR 91.155 for operational use.','14 CFR 91.155','faa-sample-derived',PAR),
  q('ppl-vfr-fuel','Regulations & Airspace','For a daytime VFR airplane flight, the planned fuel supply must allow flight to the first point of intended landing and then for at least...',['20 minutes at normal cruise','30 minutes at normal cruise','45 minutes at normal cruise'],1,'For day VFR in an airplane, 14 CFR 91.151 requires enough fuel to reach the first intended landing plus at least 30 minutes at normal cruise.','14 CFR 91.151'),
  q('ppl-lightgun','Airport Operations','While taxiing, what does a flashing white light-gun signal from the tower mean?',['Clear the runway immediately','Return to the starting point on the airport','Taxi clear of the landing area'],1,'A flashing white signal to an aircraft on the ground means return to the starting point on the airport.','AIM light-gun signal table / FAA PAR sample','faa-sample-derived',PAR),
  q('ppl-hold-short','Airport Operations','At a towered airport, when may you cross an assigned runway hold-short line?',['When your taxi clearance names the runway','Only after an explicit runway-crossing or takeoff clearance, as applicable','Any time no aircraft is visible on final'],1,'A runway hold-short line must not be crossed without the applicable explicit ATC clearance.','AIM 4-3 / runway safety'),
  q('ppl-pattern','Airport Operations','Unless otherwise indicated, standard traffic-pattern turns are normally made...',['To the left','To the right','Toward the wind'],0,'Standard traffic patterns use left turns unless right traffic is indicated by airport information, markings, or ATC.','AIM 4-3-3'),
  q('ppl-density-altitude','Weather','With pressure altitude unchanged, what happens to density altitude as outside air temperature increases?',['It decreases','It increases','It remains unchanged'],1,'Warmer air is less dense, so density altitude increases as temperature rises.','Pilot’s Handbook of Aeronautical Knowledge (PHAK)'),
  q('ppl-metar-wind','Weather','What does the METAR wind group 18018G27KT mean?',['Wind from 180° true at 18 knots, gusting 27','Wind from 018° magnetic at 27 knots','Variable wind from 180° through 270°'],0,'METAR winds are reported in degrees true. This group means 180° at 18 knots with gusts to 27 knots.','Aviation Weather Handbook'),
  q('ppl-stable','Weather','Which condition is most associated with stable air?',['Smooth air with stratiform clouds and steady precipitation','Strong vertical currents and cumuliform clouds','Showery precipitation with excellent visibility between cells'],0,'Stable air tends to produce smooth conditions, stratiform clouds, poorer visibility, and steady precipitation.','Aviation Weather Handbook'),
  q('ppl-cold-front','Weather','Compared with a warm front, a fast-moving cold front is more likely to produce...',['A narrow band of more intense weather and a rapid wind shift','Only widespread fog with no wind shift','Several days of light drizzle before passage'],0,'Fast cold fronts often produce a narrower zone of stronger vertical motion, showers or thunderstorms, gusty winds, and a sharper wind shift.','Aviation Weather Handbook'),
  q('ppl-moment','Performance & Weight/Balance','How is the moment for a loading station calculated?',['Weight multiplied by arm','Weight divided by arm','Arm divided by weight'],0,'Moment equals weight × arm. Aircraft CG is total moment divided by total weight.','PHAK weight and balance'),
  q('ppl-forward-cg','Performance & Weight/Balance','A CG near the forward limit generally causes...',['Greater longitudinal stability and higher control forces','Less longitudinal stability and lower stall speed in every condition','No effect on stability or takeoff performance'],0,'A forward CG generally increases longitudinal stability and control forces and can increase takeoff/landing performance penalties.','PHAK weight and balance'),
  q('ppl-high-da','Performance & Weight/Balance','As density altitude increases, normally aspirated airplane takeoff and climb performance generally...',['Improves','Degrades','Remains unchanged if indicated airspeed is the same'],1,'Higher density altitude reduces engine, propeller, and wing performance, generally increasing takeoff distance and reducing climb.','PHAK aircraft performance'),
  q('ppl-transponder','Systems & Airworthiness','For operations requiring a transponder, the inspection required by 14 CFR 91.413 must have been completed within the preceding...',['12 calendar months','24 calendar months','36 calendar months'],1,'The transponder inspection interval is 24 calendar months.','14 CFR 91.413','faa-sample-derived',PAR),
  q('ppl-pitot-static','Systems & Airworthiness','Which instruments use static pressure?',['Altimeter and vertical speed indicator','Tachometer and magnetic compass','Oil pressure gauge and ammeter'],0,'The altimeter and VSI use static pressure; the airspeed indicator uses both pitot and static pressure.','PHAK flight instruments'),
  q('ppl-inop-equipment','Systems & Airworthiness','A required item of equipment is found inoperative before flight. What is the correct default action?',['Ignore it if the weather is VFR','Determine whether the aircraft can be legally operated under the applicable rules, MEL/KOEL, ADs, and required equipment before flight','Pull the circuit breaker and depart'],1,'Inoperative equipment requires a legal determination under the applicable aircraft documents and regulations; VFR alone does not make required equipment optional.','14 CFR 91.213'),
  q('ppl-preflight','Navigation & Flight Planning','Before a VFR cross-country flight, 14 CFR 91.103 requires the PIC to become familiar with...',['All available information concerning the flight, including applicable weather, fuel, alternatives, runway data, and performance information','Only destination weather','Only NOTAMs and runway length'],0,'The PIC must become familiar with all available information concerning the flight, including the items specified in 91.103.','14 CFR 91.103'),
  q('ppl-variation','Navigation & Flight Planning','To convert a true course to a magnetic course, you primarily account for...',['Magnetic variation','Compass deviation only','Pressure altitude'],0,'Variation is the angular difference between true and magnetic north and is used in true/magnetic conversion.','PHAK navigation'),
  q('ppl-external-pressure','ADM & Human Factors','Weather is deteriorating and you are already late. Which response best manages external-pressure risk?',['Continue because canceling would waste the trip','Reassess margins, alternatives, and willingness to delay or divert','Increase airspeed to make up time'],1,'External pressure can drive continuation bias. Good ADM deliberately protects margins and preserves alternatives.','FAA Risk Management Handbook')
 ],
 ira:[
  q('ira-ifr-fuel','IFR Regulations','For an IFR flight under 14 CFR 91.167, fuel planning must generally allow flight to the first intended landing, then to the alternate if required, and then for...',['30 minutes at normal cruise','45 minutes at normal cruise','1 hour at best economy'],1,'The IFR reserve is 45 minutes at normal cruising speed after reaching the destination and alternate, if an alternate is required.','14 CFR 91.167'),
  q('ira-alt-rule','IFR Regulations','When is an alternate airport not required under the basic 1-2-3 rule for a Part 91 IFR flight?',['When, from 1 hour before to 1 hour after ETA, the ceiling is forecast at least 2,000 feet above airport elevation and visibility at least 3 statute miles','Whenever the destination has an ILS','Whenever the flight is less than 100 NM'],0,'The common 1-2-3 rule comes from 14 CFR 91.169: 2,000-foot ceiling and 3 SM visibility for the specified two-hour window.','14 CFR 91.169'),
  q('ira-vor-check','IFR Regulations','Before using VOR equipment for IFR operations under 14 CFR 91.171, the VOR must generally have been checked within the preceding...',['10 days','30 days','90 days'],1,'For IFR use, VOR equipment must meet the checks and tolerances in 91.171 within the preceding 30 days.','14 CFR 91.171'),
  q('ira-lost-comms-route','IFR Regulations','Under lost communications in IMC, the route priority is commonly remembered as AVEF. What does the first “A” represent?',['Assigned','Alternate','Advisory'],0,'The route order is Assigned, Vectored, Expected, Filed, subject to the exact conditions in 14 CFR 91.185.','14 CFR 91.185'),
  q('ira-static-block','Flight Instruments','If the static port becomes blocked while the pitot tube remains unobstructed, the altimeter will...',['Freeze at the altitude where the blockage occurred','Read zero','Continue to indicate normally'],0,'A blocked static source traps static pressure, causing the altimeter to remain near the altitude at which the blockage occurred.','Instrument Flying Handbook'),
  q('ira-pitot-block','Flight Instruments','If the pitot opening and drain hole both become blocked while the static system remains open, the airspeed indicator behaves most like...',['An altimeter, increasing in a climb and decreasing in a descent','A VSI, showing only rate','A magnetic compass'],0,'With trapped pitot pressure and changing static pressure, the ASI can behave like an altimeter.','Instrument Flying Handbook'),
  q('ira-vacuum-fail','Flight Instruments','In a traditional vacuum-driven attitude/heading system, a vacuum-system failure most directly threatens the...',['Attitude indicator and heading indicator','Airspeed indicator and altimeter','Turn coordinator and magnetic compass'],0,'Traditional vacuum systems commonly drive the attitude and heading indicators. Exact equipment varies by aircraft.','Instrument Flying Handbook'),
  q('ira-icing','Weather','Freezing rain is especially hazardous because it can...',['Produce rapid severe ice accumulation beyond the capability of many protection systems','Only form harmless frost on the windshield','Occur only in clear air well above freezing'],0,'Freezing rain involves supercooled large droplets and can produce rapid, severe icing.','Aviation Weather Handbook'),
  q('ira-stable-cloud','Weather','Stable moist air is most likely to produce...',['Stratiform clouds, smooth air, and reduced visibility','Cumuliform clouds with strong turbulence','Only clear skies'],0,'Stable moist air favors stratiform clouds, smoother air, and widespread reduced visibility/steady precipitation.','Aviation Weather Handbook'),
  q('ira-convective','Weather','When thunderstorms are embedded in widespread cloud layers, the safest planning assumption is that...',['Visual circumnavigation may not be possible and large margins or avoidance are required','Onboard weather radar guarantees safe passage between cells','Lightning-free gaps are safe corridors'],0,'Embedded convection removes visual avoidance cues; significant margins, datalink/radar limitations awareness, and route changes are required.','Aviation Weather Handbook / AIM'),
  q('ira-clearance','ATC & Clearances','If an IFR clearance contains a route or altitude you cannot safely accept, you should...',['Read it back and comply anyway','Tell ATC you are unable and request an amendment','Accept it, then deviate without advising ATC'],1,'A clearance is not a command to accept an unsafe operation. Advise ATC if unable and request an amended clearance.','AIM 4-4'),
  q('ira-hold-entry','Holding','Holding-pattern entry procedures published by the FAA are best described as...',['Recommended techniques; any entry that remains within protected airspace is acceptable','Mandatory maneuver names that must be flown exactly','Only applicable to GPS holds'],0,'Direct, parallel, and teardrop entries are recommended procedures; the objective is to remain within protected holding airspace.','AIM 5-3-8'),
  q('ira-hold-speed','Holding','At or below 6,000 feet MSL, the standard maximum holding airspeed is generally...',['200 KIAS','230 KIAS','265 KIAS'],0,'Standard holding maximum is generally 200 KIAS at or below 6,000 feet, unless otherwise published.','AIM 5-3-8'),
  q('ira-rnav-lpv','Approaches','To fly an RNAV (GPS) approach to LPV minimums, the aircraft needs...',['An approved WAAS-capable installation authorized for LPV','Any handheld GPS','Only DME and VOR receivers'],0,'LPV service requires appropriately approved WAAS-capable equipment and authorization.','AIM GPS/RNAV operations'),
  q('ira-da-mda','Approaches','Which statement correctly distinguishes a decision altitude (DA) from a minimum descent altitude (MDA)?',['A DA is used on approaches with vertical guidance and is a decision point; an MDA is a minimum altitude that is not descended below until required visual references exist','An MDA applies only to ILS approaches','A DA is always lower than an MDA'],0,'DA is associated with approaches providing approved vertical guidance; MDA is used for nonprecision-style procedures and is not descended below without required visual references.','AIM 5-4'),
  q('ira-missed','Approaches','If required visual references are not available at the appropriate point on an instrument approach, the pilot should...',['Continue below minimums for a better look','Execute the published missed approach or an ATC-assigned missed procedure','Circle regardless of weather'],1,'When the requirements to continue are not met, execute the missed approach as required.','14 CFR 91.175 / AIM'),
  q('ira-ils-components','Approaches','Which pair provides the primary lateral and vertical guidance on an ILS?',['Localizer and glideslope','VOR and DME','ADF and marker beacon'],0,'The localizer provides lateral guidance and the glideslope provides vertical guidance.','Instrument Flying Handbook'),
  q('ira-vor-tofrom','Navigation','A VOR CDI centered with a TO indication means the selected course...',['If flown inbound while maintaining course, leads toward the station','Always means the aircraft is north of the station','Shows only bearing, not course information'],0,'With proper interpretation, a centered CDI and TO indication identifies a selected course leading to the station.','Instrument Flying Handbook'),
  q('ira-gps-raim','Navigation','For non-WAAS IFR GPS operations, RAIM is primarily used to...',['Monitor integrity of the GPS solution','Increase transmitter power','Provide weather radar returns'],0,'RAIM is an integrity-monitoring function used by applicable GPS installations.','AIM GPS'),
  q('ira-scan','Human Factors','During instrument flight, fixation on a single instrument is best countered by...',['A disciplined instrument scan and cross-check','Turning off the other displays','Ignoring trend information'],0,'A systematic cross-check reduces fixation and helps detect instrument or performance deviations.','Instrument Flying Handbook')
 ],
 cpl:[
  q('cpl-part119','Commercial Privileges & Regulations','Which operation is generally among those excepted from needing a Part 119 operating certificate when conducted within the applicable conditions?',['Scheduled passenger service','Aerial photography or crop-dusting work','On-demand passenger charter'],1,'Certain aerial work operations are excepted by 14 CFR 119.1(e), although other rules still apply.','14 CFR 119.1','faa-sample-derived',CAX),
  q('cpl-common-carriage','Commercial Privileges & Regulations','A pilot holding only a commercial pilot certificate may not simply advertise to the public and transport passengers for compensation because that can involve...',['Common carriage and operating-certificate requirements','Only a medical-certificate issue','A prohibition on all compensated flying'],0,'Holding a commercial pilot certificate does not by itself authorize common carriage. Operating authority and certification requirements may apply.','14 CFR Parts 61, 119, 121/135'),
  q('cpl-high-performance','Commercial Privileges & Regulations','To act as PIC of a high-performance airplane, a pilot generally needs...',['Ground and flight training plus an appropriate logbook endorsement, unless an exception applies','Only a complex-airplane endorsement','Five hours of turbine time'],0,'14 CFR 61.31 requires appropriate training and an endorsement for high-performance airplanes unless an exception applies.','14 CFR 61.31'),
  q('cpl-class-e','Airspace & Operations','Above 10,000 feet MSL in Class E airspace, minimum VFR flight visibility is...',['3 statute miles','5 statute miles','1 statute mile'],1,'VFR above 10,000 feet MSL in Class E requires 5 SM visibility and greater cloud clearances.','14 CFR 91.155','faa-sample-derived',CAX),
  q('cpl-preflight','Airspace & Operations','For a cross-country flight, 14 CFR 91.103 requires the PIC to become familiar with...',['All available information concerning the flight','Only the departure weather','Only the destination runway length'],0,'Preflight action includes all available information concerning the flight and specified weather, fuel, alternatives, runway, and performance data.','14 CFR 91.103','faa-sample-derived',CAX),
  q('cpl-unstable','Weather','Which air mass is most associated with atmospheric instability?',['Cool and dry','Warm and humid','Strongly descending air'],1,'Warm, moist air is more likely to be unstable when lifted.','Aviation Weather Handbook / FAA CAX sample','faa-sample-derived',CAX),
  q('cpl-coldfront','Weather','After passage of a fast-moving cold front, which conditions are commonly expected?',['Cooler air, gusty/turbulent winds, and improving ceilings behind the front','Warmer temperatures and calm winds','Several days of warm drizzle'],0,'Fast cold fronts often leave cooler air, gusty winds, and improving ceilings after passage.','Aviation Weather Handbook / FAA CAX sample','faa-sample-derived',CAX),
  q('cpl-radar','Weather','Airborne weather radar is best used to...',['Identify precipitation intensity and support avoidance decisions, while recognizing attenuation and other limitations','Guarantee a turbulence-free route between echoes','Detect all clouds regardless of moisture'],0,'Weather radar detects precipitation energy, not all hazards, and is subject to attenuation and interpretation limitations.','Aviation Weather Handbook / FAA CAX sample','faa-sample-derived',CAX),
  q('cpl-downwind','Performance & Aerodynamics','A downwind landing, compared with landing into the wind, generally results in...',['Higher groundspeed and increased landing distance','Lower groundspeed and shorter landing distance','No change in groundspeed'],0,'A tailwind increases groundspeed for the same approach airspeed and generally increases landing distance.','Airplane Flying Handbook / FAA CAX sample','faa-sample-derived',CAX),
  q('cpl-loadfactor','Performance & Aerodynamics','In a coordinated level 60° banked turn, the approximate load factor is...',['1.4 G','2.0 G','3.0 G'],1,'A coordinated level 60° bank produces a load factor of about 2 G.','PHAK aerodynamics'),
  q('cpl-stall-load','Performance & Aerodynamics','As load factor increases, stall speed...',['Increases','Decreases','Is unaffected'],0,'Stall speed increases with the square root of load factor.','PHAK aerodynamics'),
  q('cpl-groundeffect','Performance & Aerodynamics','Ground effect primarily reduces...',['Induced drag','Parasite drag to zero','Aircraft weight'],0,'Near the surface, wingtip-vortex and downwash effects are reduced, lowering induced drag.','PHAK aerodynamics'),
  q('cpl-zero-thrust','Performance & Aerodynamics','A windmilling propeller on an inoperative engine generally produces...',['More drag than a feathered propeller','Less drag than a feathered propeller','No drag'],0,'A windmilling propeller creates substantial drag; feathering aligns blades more closely with the airflow and reduces drag.','Airplane Flying Handbook'),
  q('cpl-co','Systems & Airworthiness','Why must exhaust-based cabin-heating systems be inspected carefully?',['A crack can allow carbon monoxide into cabin air','A crack causes the altimeter to freeze','A crack makes the battery overcharge'],0,'Exhaust-system defects can introduce carbon monoxide into cabin heating air.','PHAK / FAA CAX sample','faa-sample-derived',CAX),
  q('cpl-ad','Systems & Airworthiness','An applicable Airworthiness Directive is overdue. What is the correct default decision?',['Do not operate until compliance or a specific legal provision permits operation','Fly VFR only','Use a 10-hour automatic grace period'],0,'Applicable ADs are mandatory unless the AD or another specific authorization allows otherwise.','14 CFR 39'),
  q('cpl-constant-speed','Systems & Airworthiness','In a constant-speed propeller system, the governor primarily maintains selected RPM by changing...',['Blade angle','Mixture ratio','Ignition timing'],0,'The governor adjusts propeller blade angle to maintain selected RPM within the system’s operating range.','PHAK propeller systems'),
  q('cpl-turbo','Systems & Airworthiness','A turbocharger wastegate controls...',['The amount of exhaust gas directed through the turbine','Fuel flow directly to the cylinders','Propeller blade angle'],0,'The wastegate regulates exhaust-gas flow through the turbocharger turbine and therefore boost.','PHAK engine systems'),
  q('cpl-critical-mach','High-Speed Aerodynamics','Exceeding critical Mach can cause...',['Shock waves, buffet, drag rise, and control difficulties','Automatic propeller feathering','A guaranteed increase in lift with no drag penalty'],0,'Compressibility effects above critical Mach can produce shock waves, buffet, drag rise, and control changes.','PHAK high-speed flight / FAA CAX sample','faa-sample-derived',CAX),
  q('cpl-cg-aft','Weight & Balance','Moving the CG aft within limits generally...',['Reduces longitudinal stability','Increases longitudinal stability','Has no effect on stability'],0,'An aft CG reduces the tail-down force and generally reduces longitudinal stability.','PHAK weight and balance'),
  q('cpl-adm','ADM & Operations','A passenger insists on arriving on time despite deteriorating weather. The strongest commercial-pilot response is to...',['Protect the safety margin and change, delay, divert, or cancel the plan as needed','Continue because customer expectations determine the go/no-go decision','Lower personal weather minimums because compensation is involved'],0,'Commercial pressure is an external-pressure hazard; the pilot must preserve legal and safe margins.','FAA Risk Management Handbook')
 ],
 cfi:[
  q('cfi-learning','Learning Process','Learning is best described as...',['A change in behavior as a result of experience','Temporary memorization with no change in performance','Only the ability to pass a written test'],0,'FAA instructor guidance treats learning as a change in behavior resulting from experience.','Aviation Instructor’s Handbook','faa-sample-derived',FIA),
  q('cfi-laws','Learning Process','Which principle says things most recently learned are often best remembered?',['Law of recency','Law of intensity','Law of primacy'],0,'The law of recency emphasizes that recently learned material tends to be remembered best.','Aviation Instructor’s Handbook'),
  q('cfi-primacy','Learning Process','Why is primacy especially important in flight instruction?',['The first way a skill is learned can create a strong, persistent impression','Students never remember later corrections','It means the first lesson must always be a solo flight'],0,'First learning often creates a strong impression, so instructors should teach the correct concept or procedure from the beginning.','Aviation Instructor’s Handbook'),
  q('cfi-readiness','Learning Process','The law of readiness suggests learning is most effective when the learner...',['Is physically and mentally ready and sees a reason to learn','Is surprised with material without preparation','Receives only negative reinforcement'],0,'Readiness supports motivation and the learner’s capacity to engage with the task.','Aviation Instructor’s Handbook'),
  q('cfi-defense','Human Behavior','A student blames every poor landing on wind, equipment, or other people. This most closely resembles...',['Projection','Compensation','Sublimation'],0,'Projection attributes one’s own shortcomings or unacceptable traits to someone or something else.','Aviation Instructor’s Handbook'),
  q('cfi-communication','Communication','Effective communication requires the instructor to...',['Encode a message, transmit it through a medium, and check the learner’s understanding/feedback','Deliver information without feedback','Use technical jargon whenever possible'],0,'Communication is not complete just because words were spoken; feedback helps confirm the message was understood.','Aviation Instructor’s Handbook'),
  q('cfi-question','Teaching Process','A good instructional question should generally...',['Be clear, concise, and focused on a definite purpose','Contain the answer in the wording','Be intentionally ambiguous'],0,'Effective questions are clear, relevant, and designed to stimulate thought or check understanding.','Aviation Instructor’s Handbook'),
  q('cfi-assessment','Assessment','A useful critique should be...',['Specific, objective, constructive, and tied to standards','Personal and focused on the learner’s character','Delayed until the end of the course regardless of the event'],0,'Effective assessment focuses on observable performance and gives specific information the learner can use.','Aviation Instructor’s Handbook'),
  q('cfi-scenario','Teaching Process','Scenario-based training is most valuable when it...',['Requires the learner to apply knowledge and make decisions in realistic context','Replaces all maneuver practice','Avoids discussion of risk'],0,'Scenarios help learners integrate technical knowledge, risk management, and decision making.','Aviation Instructor’s Handbook'),
  q('cfi-rote','Learning Process','Rote learning is primarily the ability to...',['Repeat facts or procedures without necessarily understanding relationships','Apply knowledge automatically to new situations','Evaluate alternatives and defend a decision'],0,'Rote is the lowest learning level: remembering or repeating information.','Aviation Instructor’s Handbook'),
  q('cfi-correlation','Learning Process','At the correlation level, a learner can...',['Associate learned elements with other segments of learning and apply them to new situations','Only repeat memorized facts','Perform a maneuver only with instructor prompting'],0,'Correlation is the highest classic level in FAA learning descriptions, where knowledge transfers to new contexts.','Aviation Instructor’s Handbook'),
  q('cfi-demo-performance','Flight Instruction','In the demonstration-performance method, the instructor should first...',['Explain and demonstrate the skill before supervised student performance and evaluation','Have the student perform the maneuver with no briefing','Evaluate before demonstrating'],0,'The classic sequence is explanation, demonstration, student performance, instructor supervision, and evaluation.','Aviation Instructor’s Handbook'),
  q('cfi-integrated','Flight Instruction','Integrated flight instruction means teaching students to...',['Use outside references and flight instruments together from the beginning','Fly solely by instruments on every lesson','Ignore instrument indications during visual maneuvers'],0,'Integrated instruction develops coordinated use of outside visual references and flight instruments.','Aviation Instructor’s Handbook'),
  q('cfi-distraction','Risk Management','When teaching a student to manage cockpit distractions, the instructor should...',['Introduce realistic distractions at appropriate times without compromising safety','Create maximum distraction during the student’s first takeoff','Avoid discussing distractions entirely'],0,'Distraction training should be deliberate, realistic, and introduced with safety and learner readiness in mind.','Aviation Instructor’s Handbook'),
  q('cfi-endorsement','Instructor Responsibilities','Before giving a required endorsement, an instructor should...',['Ensure the applicant has received the required training and meets the applicable standard','Sign it whenever the learner requests it','Use a generic endorsement unrelated to the regulation'],0,'An endorsement is the instructor’s certification that specified requirements have been met.','14 CFR Part 61 / AC 61-65'),
  q('cfi-logbook','Instructor Responsibilities','Flight instructors are required to keep certain endorsement and training records for at least...',['1 year','3 years','10 years'],1,'14 CFR 61.189 requires specified instructor records to be retained for 3 years.','14 CFR 61.189'),
  q('cfi-stall','Aerodynamics & Maneuvers','An aerodynamic stall occurs when the wing...',['Exceeds its critical angle of attack','Drops below a specific airspeed in all configurations','Reaches zero lift'],0,'A stall is fundamentally an angle-of-attack event; airspeed at stall varies with load factor and configuration.','Airplane Flying Handbook'),
  q('cfi-crosscontrol','Aerodynamics & Maneuvers','A cross-controlled stall near the ground is especially hazardous because it can...',['Produce rapid autorotation toward a spin with little altitude for recovery','Prevent the airplane from rolling','Automatically lower angle of attack'],0,'Yaw plus stall can produce rapid autorotation; base-to-final overshoot corrections are a classic risk context.','Airplane Flying Handbook'),
  q('cfi-secondary','Aerodynamics & Maneuvers','A secondary stall during recovery usually results from...',['Applying excessive back pressure before the wing has fully recovered from the first stall','Reducing angle of attack too much','Using insufficient rudder during taxi'],0,'Trying to recover altitude too aggressively can again exceed critical angle of attack and cause a secondary stall.','Airplane Flying Handbook'),
  q('cfi-professionalism','Instructor Responsibilities','Instructor professionalism is best demonstrated by...',['Modeling safe, ethical behavior and maintaining technical competence','Using fear to force compliance','Avoiding admission of uncertainty'],0,'Professional instructors model sound judgment, competence, integrity, and continuous learning.','Aviation Instructor’s Handbook')
 ],
 cfii:[
  q('cfii-alt','IFR Regulations','The 1-2-3 alternate rule is primarily used to determine...',['Whether an alternate airport must be filed under Part 91 IFR','Whether a VOR check is required','Whether a flight plan may be canceled'],0,'The 1-2-3 criteria in 14 CFR 91.169 determine when an alternate is required for many Part 91 IFR flights.','14 CFR 91.169'),
  q('cfii-vor','IFR Regulations','A student asks how often an IFR VOR check is required. The correct response is...',['Within the preceding 30 days when the VOR is used under IFR','Every 24 calendar months','Only after maintenance'],0,'14 CFR 91.171 sets the 30-day VOR-check interval and allowable methods/tolerances.','14 CFR 91.171'),
  q('cfii-91-175','IFR Regulations','To descend below DA/MDA under 14 CFR 91.175, the required elements include...',['Required flight visibility, required visual reference, and a position from which a normal descent to landing can be made','Only seeing any airport light','Only ATC approval'],0,'The regulation requires specified visibility, visual references, and a position permitting a normal landing descent.','14 CFR 91.175'),
  q('cfii-static','Instrument Systems','A blocked static source can make the altimeter...',['Freeze near the altitude at which blockage occurred','Indicate zero regardless of altitude','Operate normally because it uses pitot pressure'],0,'The altimeter depends on changing static pressure; trapped static pressure causes it to freeze near the blockage altitude.','Instrument Flying Handbook'),
  q('cfii-pitot','Instrument Systems','With pitot pressure trapped and static pressure still changing, the airspeed indicator may...',['Act like an altimeter','Act like a magnetic compass','Read zero in every phase of flight'],0,'If pitot pressure is trapped, changing static pressure can make the ASI increase in climbs and decrease in descents.','Instrument Flying Handbook'),
  q('cfii-ahrs','Instrument Systems','In a modern glass cockpit, an AHRS primarily supplies...',['Attitude and heading information','Fuel flow and oil pressure only','Weather radar returns'],0,'AHRS replaces traditional spinning gyros for attitude/heading sensing in many integrated avionics systems.','Instrument Flying Handbook'),
  q('cfii-ice','Weather Instruction','When teaching icing avoidance, freezing rain should be presented as...',['A potentially severe icing condition requiring strong avoidance/exit planning','A minor nuisance if pitot heat is on','A condition that occurs only below clouds'],0,'Freezing rain can contain supercooled large droplets and cause severe icing.','Aviation Weather Handbook'),
  q('cfii-convection','Weather Instruction','A key limitation to teach about datalink weather is that...',['It is not real-time tactical thunderstorm avoidance data','It shows every cell with no latency','It can replace onboard weather radar at close range'],0,'Datalink products have age/latency and are strategic, not tactical, tools for thunderstorm avoidance.','AIM / Aviation Weather Handbook'),
  q('cfii-temp','Weather Instruction','A temperature inversion usually indicates...',['A stable layer that can trap moisture, haze, and pollutants','Extreme instability throughout the layer','Guaranteed severe turbulence'],0,'An inversion is stable and can trap moisture or contaminants below it.','Aviation Weather Handbook'),
  q('cfii-clearance','ATC & Procedures','A student receives an IFR clearance that cannot be safely accepted. The best instruction is to...',['Advise ATC “unable” and request an amendment','Accept it and plan to deviate later','Remain silent and ignore the clearance'],0,'Pilots should not accept a clearance they cannot safely or legally comply with.','AIM 4-4'),
  q('cfii-hold','Holding Instruction','Holding entries are best taught as...',['Recommended techniques whose goal is remaining within protected airspace','Mandatory names that ATC grades','Procedures used only with VORs'],0,'FAA holding entries are recommended techniques; protected-airspace containment is the operational goal.','AIM 5-3-8'),
  q('cfii-timing','Holding Instruction','Standard holding-pattern leg timing at or below 14,000 feet MSL is generally...',['1 minute inbound','1.5 minutes inbound','2 minutes inbound'],0,'Standard inbound leg timing is generally 1 minute at or below 14,000 feet MSL unless distance is published.','AIM 5-3-8'),
  q('cfii-lpv','Approach Instruction','LPV minimums require...',['Approved WAAS-capable equipment and authorization','A handheld GPS only','DME but no GPS'],0,'LPV relies on WAAS and requires appropriately approved equipment.','AIM RNAV/GPS'),
  q('cfii-vdp','Approach Instruction','A visual descent point (VDP) is intended to help a pilot...',['Begin a normal descent from MDA to the runway when required visual references exist','Determine the missed-approach holding speed','Identify the final approach fix on an ILS'],0,'A VDP provides a visual cue for beginning a normal descent from MDA to the runway if visual requirements are met.','AIM 5-4'),
  q('cfii-circling','Approach Instruction','Circling approach protected areas are based partly on...',['Approach category and obstacle-clearance criteria','Only runway length','Only aircraft weight'],0,'Circling protection depends on approach category and published circling design criteria.','Instrument Procedures Handbook'),
  q('cfii-partialpanel','Teaching Technique','A strong partial-panel lesson should emphasize...',['Recognition, cross-check, control using reliable instruments, and workload management','Covering random instruments without briefing or safety planning','Memorizing one fixed scan for every avionics suite'],0,'Effective partial-panel instruction builds failure recognition, reliable-instrument use, and sound workload/decision management.','Instrument Flying Handbook / Aviation Instructor’s Handbook'),
  q('cfii-fixation','Teaching Technique','A student fixates on the attitude indicator and misses altitude and heading trends. The best correction is to emphasize...',['A purposeful cross-check and interpretation of supporting instruments','Looking at the attitude indicator even longer','Ignoring performance instruments'],0,'A disciplined cross-check counters fixation and helps the learner relate control and performance information.','Instrument Flying Handbook'),
  q('cfii-chasing','Teaching Technique','A student repeatedly chases needles with large control inputs on final. The best teaching emphasis is...',['Small corrections, trend recognition, and returning to a stable attitude/power baseline','Larger and faster control inputs','Ignoring the localizer until minimums'],0,'Instrument precision improves when students recognize trends early and make small corrections around a stable baseline.','Instrument Flying Handbook'),
  q('cfii-brief','Teaching Technique','An effective instrument approach briefing should primarily...',['Build a shared mental model of course, altitudes, minimums, missed approach, and threats','Read every printed word with no prioritization','Focus only on the runway number'],0,'A useful briefing highlights operationally relevant elements and anticipated threats.','Instrument Procedures Handbook'),
  q('cfii-risk','Risk Management','A CFII should teach personal minimums as...',['Preplanned risk controls that can be more conservative than regulatory minimums','A substitute for regulations','A reason to ignore changing conditions'],0,'Personal minimums support risk management and may be more conservative than legal minima; they do not replace regulations.','FAA Risk Management Handbook')
 ],
 atp:[
  q('atp-dispatch','Air Carrier Regulations','In domestic Part 121 operations, who shares responsibility with the PIC for preflight planning, delays, and the dispatch release?',['Aircraft dispatcher','Chief pilot','Director of maintenance'],0,'The aircraft dispatcher and PIC share operational-control responsibilities defined by Part 121 and the operator’s system.','14 CFR Part 121 / FAA ATM sample','faa-sample-derived',ATM),
  q('atp-alt','Air Carrier Regulations','A Part 121 alternate airport must satisfy forecast weather criteria based primarily on...',['The operator’s approved alternate weather minima in its operations specifications','Only the lowest published approach minimum','Basic VFR minimums'],0,'Part 121 alternate planning uses company OpSpecs and applicable regulations.','14 CFR Part 121 / OpSpecs','faa-sample-derived',ATM),
  q('atp-sterile','Air Carrier Regulations','The sterile-cockpit rule is intended primarily to...',['Limit nonessential activities during critical phases of flight','Prohibit all communication below 10,000 feet','Apply only during taxi'],0,'Sterile-cockpit requirements reduce distraction during critical phases of flight.','14 CFR 121.542'),
  q('atp-121-fuel','Air Carrier Regulations','Part 121 dispatch fuel requirements are best described as...',['Operation-specific requirements that include trip fuel plus applicable reserve, alternate, and additional fuel provisions','Exactly 45 minutes for every flight','Identical to Part 91 VFR fuel rules'],0,'Air-carrier fuel planning depends on the operation and applicable Part 121 rules and OpSpecs.','14 CFR Part 121'),
  q('atp-slats','High-Altitude Aerodynamics','Extending leading-edge slats generally...',['Increases maximum lift coefficient and delays separation','Eliminates induced drag','Reduces maximum lift coefficient'],0,'Slats help the wing sustain attached flow at higher angle of attack and increase maximum lift.','PHAK / FAA ATM sample','faa-sample-derived',ATM),
  q('atp-weight-climb','High-Altitude Performance','Increasing aircraft weight generally...',['Reduces climb performance','Improves climb performance','Has no effect on required lift'],0,'More weight requires more lift and usually more induced drag, reducing excess thrust/power available for climb.','Airplane Flying Handbook / FAA ATM sample','faa-sample-derived',ATM),
  q('atp-coffin','High-Altitude Aerodynamics','At very high altitude, the margin between low-speed buffet and high-speed Mach buffet may...',['Narrow significantly','Always increase','Become unrelated to aircraft weight'],0,'As altitude increases, the low-speed and high-speed buffet boundaries can converge, reducing maneuver margin.','PHAK high-altitude flight'),
  q('atp-mach-tuck','High-Altitude Aerodynamics','Mach tuck is associated with...',['An aft shift of center of pressure and a nose-down pitching tendency as compressibility effects increase','A guaranteed nose-up tendency from flap extension','Loss of all rudder authority at low speed'],0,'Compressibility and shock effects can move the center of pressure aft and create a nose-down pitching tendency.','PHAK high-speed aerodynamics'),
  q('atp-zero-fuel','Weight & Performance','A maximum zero-fuel-weight limitation primarily protects against excessive...',['Wing-root bending loads with heavy fuselage payload and low wing fuel','Tire pressure','Cabin differential pressure'],0,'Fuel in wing tanks provides bending relief; zero-fuel-weight limits protect structural bending loads.','Transport-category weight and balance / FAA ATM sample','faa-sample-derived',ATM),
  q('atp-hotstart','Turbine Systems','A turbine-engine hot start commonly results when...',['Fuel is introduced without enough compressor airflow/RPM','The engine receives too much ram air at cruise','Oil temperature is too low after shutdown'],0,'Insufficient airflow during light-off can cause rapid EGT/ITT rise beyond limits.','FAA turbine engine guidance / FAA ATM sample','faa-sample-derived',ATM),
  q('atp-compressor','Turbine Systems','A compressor stall may be indicated by...',['Loud bangs, vibration, yaw, and abnormal engine indications','A perfectly steady engine with lower cabin altitude','Only a change in hydraulic quantity'],0,'Compressor stalls/surges can produce bangs, airflow disruption, vibration, yaw, and abnormal temperature/RPM indications.','PHAK turbine engines'),
  q('atp-bleed','Turbine Systems','Bleed air in transport airplanes is commonly used for...',['Pressurization, air conditioning, and anti-ice functions','Direct lubrication of bearings','Primary electrical generation only'],0,'Compressed bleed air is widely used for pneumatic services including pressurization, environmental control, and anti-ice.','Transport aircraft systems'),
  q('atp-press','Turbine Systems','Cabin altitude begins climbing unexpectedly at cruise. The crew’s first priority is to...',['Recognize the pressurization problem, use required oxygen as needed, and follow the approved checklist','Open all cabin doors','Increase cabin differential pressure manually without reference to procedures'],0,'Pressurization events require prompt recognition, oxygen use when required, and checklist/QRH execution.','Aircraft QRH / high-altitude operations'),
  q('atp-lpv','IFR Procedures','An RNAV (GPS) approach to LPV minimums requires...',['Approved WAAS-capable equipment authorized for LPV','Any portable GPS','A VOR receiver only'],0,'LPV uses SBAS/WAAS-based angular guidance and requires approved equipment.','AIM / FAA ATM sample','faa-sample-derived',ATM),
  q('atp-holdbank','IFR Procedures','For normal holding with a flight director, bank is commonly limited to...',['Standard rate or 25°, whichever is less','45° minimum','10° regardless of speed'],0,'Standard holding guidance commonly uses 3°/second or 25° of bank, whichever is less.','AIM / FAA ATM sample','faa-sample-derived',ATM),
  q('atp-cat','IFR Procedures','Approach category is fundamentally based on...',['A reference speed derived from VSO or VS1G as defined by the applicable criteria','Aircraft maximum takeoff weight only','Number of engines only'],0,'Approach categories are speed-based and determine procedure protection/minima applicability.','AIM / TERPS concepts'),
  q('atp-hypervent','Human Factors & CRM','Which symptom is commonly associated with hyperventilation?',['Tingling and lightheadedness','Improved night vision','A lower breathing rate without intervention'],0,'Hyperventilation can cause tingling, dizziness/lightheadedness, visual changes, and degraded performance.','AIM aeromedical factors / FAA ATM sample','faa-sample-derived',ATM),
  q('atp-risk','Human Factors & CRM','Risk assessment is commonly framed around...',['Likelihood and severity','Convenience and cost','Seniority and schedule'],0,'Risk matrices commonly evaluate probability/likelihood and severity of consequences.','FAA Safety Management / FAA ATM sample','faa-sample-derived',ATM),
  q('atp-crm','Human Factors & CRM','Effective CRM encourages first officers to...',['Speak up clearly when they identify a safety threat and continue appropriate advocacy if unresolved','Remain silent if the captain has more experience','Avoid cross-checking captain actions'],0,'CRM relies on communication, monitoring, challenge-and-response, workload management, and appropriate assertiveness.','FAA CRM guidance'),
  q('atp-freezing-rain','Weather & Airport Operations','A transport-category crew encountering freezing rain should treat it as...',['A potentially severe icing hazard and follow approved avoidance/exit procedures','Benign if wing anti-ice is on','A condition that cannot occur above the freezing level'],0,'Freezing rain can produce severe icing and may exceed protection-system capability.','Aviation Weather Handbook'),
  q('atp-rwsl','Weather & Airport Operations','Runway Status Lights are driven by airport-surface surveillance such as...',['ASDE-X or ASSC','The aircraft TCAS only','A manual cockpit switch'],0,'RWSL uses airport-surface surveillance data to provide direct runway-occupancy/status cues.','FAA runway safety / FAA ATM sample','faa-sample-derived',ATM)
 ]
};

export const publicSources={testing:FAA_TESTING,acs:FAA_ACS,handbooks:FAA_PILOT_HANDBOOKS};
