import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {banks,trackMeta,publicSources,bankManifest,type Track,type PrepQuestion,type Difficulty} from './bank.ts';

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const json=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers:cors});
const validTrack=(v:unknown):Track=>['ppl','ira','cpl','cfi','cfii','atp'].includes(String(v))?String(v) as Track:'ppl';
const validMode=(v:unknown)=>['learn','random','missed','marked','exam'].includes(String(v))?String(v):'learn';
const validDifficulty=(v:unknown):Difficulty|'all'=>['foundation','applied','advanced'].includes(String(v))?String(v) as Difficulty:'all';
const nowIso=()=>new Date().toISOString();
const enc=(v:string)=>encodeURIComponent(v);
const grade=(v:number)=>v>=90?'A':v>=80?'B':v>=70?'C':v>=60?'D':'F';

function shuffle<T>(input:T[]):T[]{const a=[...input];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function prepareQuestion(q:PrepQuestion){const indexed=q.options.map((text,index)=>({text,index}));const mixed=shuffle(indexed);return {...q,options:mixed.map(x=>x.text),correct:mixed.findIndex(x=>x.index===q.correct)}}
function publicQuestion(q:any,index:number,total:number,bookmarked=false){return {id:q.id,area:q.area,prompt:q.prompt,options:q.options,source:q.source,sourceUrl:q.sourceUrl||null,figureRef:q.figureRef||null,index,total,bookmarked,standardCode:q.standardCode,standardDoc:q.standardDoc,standardType:q.standardType,difficulty:q.difficulty,experienceLevel:q.experienceLevel,reviewedAt:q.reviewedAt||null}}
function nextDue(streak:number,correct:boolean){const d=new Date();if(!correct){d.setMinutes(d.getMinutes()+10);return d.toISOString()}const days=streak<=1?1:streak===2?3:streak===3?7:streak===4?14:30;d.setDate(d.getDate()+days);return d.toISOString()}
function mastery(correct:number,total:number,streak:number){if(!total)return 0;return Math.min(100,Math.round(((correct/total)*72+Math.min(streak,5)*5.6)*100)/100)}

async function authUser(base:string,anon:string,req:Request){const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)return null;const r=await fetch(`${base}/auth/v1/user`,{headers:{apikey:anon,Authorization:`Bearer ${token}`}});if(!r.ok)return null;const u=await r.json();return u?.id?u:null}
async function rest(base:string,headers:Record<string,string>,path:string,init:RequestInit={}){return fetch(`${base}/rest/v1/${path}`,{...init,headers:{...headers,...(init.headers||{})}})}
async function getStats(base:string,h:Record<string,string>,userId:string,track:Track){const r=await rest(base,h,`written_prep_stats?select=*&user_id=eq.${enc(userId)}&track=eq.${track}`);return r.ok?await r.json():[]}
async function getBookmarks(base:string,h:Record<string,string>,userId:string,track:Track){const r=await rest(base,h,`written_prep_bookmarks?select=question_id&user_id=eq.${enc(userId)}&track=eq.${track}`);return r.ok?(await r.json()).map((x:any)=>x.question_id):[]}
async function recentSessions(base:string,h:Record<string,string>,userId:string,track:Track){const r=await rest(base,h,`written_prep_sessions?select=id,mode,difficulty,score,answered,total,completed_at,created_at&user_id=eq.${enc(userId)}&track=eq.${track}&completed_at=not.is.null&order=completed_at.desc&limit=8`);return r.ok?await r.json():[]}
async function activeSession(base:string,h:Record<string,string>,userId:string,track:Track){const r=await rest(base,h,`written_prep_sessions?select=*&user_id=eq.${enc(userId)}&track=eq.${track}&completed_at=is.null&order=created_at.desc&limit=1`);if(!r.ok)return null;const rows=await r.json();return rows?.[0]||null}

function statGroups(stats:any[],qMap:Map<string,PrepQuestion>){
 const byArea=new Map<string,any>(),byStandard=new Map<string,any>(),byDifficulty=new Map<string,any>();
 const add=(map:Map<string,any>,key:string,label:string,stat:any,q:PrepQuestion)=>{const v=map.get(key)||{key,label,correct:0,total:0,mastery:0,n:0,standardDoc:q.standardDoc,standardType:q.standardType};v.correct+=Number(stat.correct_count||0);v.total+=Number(stat.total_count||0);v.mastery+=Number(stat.mastery||0);v.n++;map.set(key,v)};
 for(const s of stats){const q=qMap.get(s.question_id);if(!q)continue;add(byArea,q.area,q.area,s,q);add(byStandard,q.standardCode,q.standardCode,s,q);add(byDifficulty,q.difficulty,q.difficulty,s,q)}
 const finish=(map:Map<string,any>)=>[...map.values()].map(v=>({...v,percent:v.total?Math.round(v.correct/v.total*100):0,mastery:Math.round(v.mastery/Math.max(1,v.n))}));
 return {areas:finish(byArea).sort((a,b)=>a.mastery-b.mastery||a.label.localeCompare(b.label)),standards:finish(byStandard).sort((a,b)=>a.mastery-b.mastery||a.label.localeCompare(b.label)),difficulties:finish(byDifficulty).sort((a,b)=>['foundation','applied','advanced'].indexOf(a.key)-['foundation','applied','advanced'].indexOf(b.key))};
}
function buildDashboard(track:Track,stats:any[],bookmarks:string[],sessions:any[],difficulty:Difficulty|'all'){
 const full=banks[track],bank=difficulty==='all'?full:full.filter(q=>q.difficulty===difficulty),allowed=new Set(bank.map(q=>q.id)),filteredStats=stats.filter((s:any)=>allowed.has(s.question_id)),qMap=new Map(full.map(q=>[q.id,q]));
 const attempted=filteredStats.length,totalAnswers=filteredStats.reduce((s:number,x:any)=>s+Number(x.total_count||0),0),correct=filteredStats.reduce((s:number,x:any)=>s+Number(x.correct_count||0),0),accuracy=totalAnswers?Math.round(correct/totalAnswers*100):0,coverage=bank.length?Math.round(attempted/bank.length*100):0,due=filteredStats.filter((x:any)=>new Date(x.due_at)<=new Date()).length,missedStats=filteredStats.filter((x:any)=>x.last_result===false),missed=missedStats.length,readiness=Math.round(accuracy*.65+coverage*.35),groups=statGroups(filteredStats,qMap),missedMap=new Map<string,number>();
 for(const s of missedStats){const area=qMap.get(s.question_id)?.area||String(s.skill_area||'Other');missedMap.set(area,(missedMap.get(area)||0)+1)}
 const missedByArea=[...missedMap.entries()].map(([area,count])=>({area,count})).sort((a,b)=>b.count-a.count||a.area.localeCompare(b.area));
 const availableCodes=new Set(bank.map(q=>q.standardCode)),attemptedCodes=new Set(filteredStats.map((s:any)=>qMap.get(s.question_id)?.standardCode).filter(Boolean)),standardCoverage=availableCodes.size?Math.round(attemptedCodes.size/availableCodes.size*100):0;
 return {track,difficulty,meta:trackMeta[track],bankSize:bank.length,fullBankSize:full.length,attempted,totalAnswers,accuracy,coverage,readiness,grade:grade(readiness),passingReadiness:readiness>=Number(trackMeta[track].passingScore||70),standardCoverage,due,missed,missedByArea,bookmarked:bookmarks.filter(id=>allowed.has(id)).length,completedSessions:sessions.length,skillAreas:groups.areas,standardBreakdown:groups.standards,difficultyBreakdown:groups.difficulties,recentSessions:sessions,sources:publicSources,bankManifest,contentReviewed:'2026-09'};
}
async function dashboard(base:string,h:Record<string,string>,userId:string,track:Track,difficulty:Difficulty|'all'){const [stats,bookmarks,sessions,active]=await Promise.all([getStats(base,h,userId,track),getBookmarks(base,h,userId,track),recentSessions(base,h,userId,track),activeSession(base,h,userId,track)]);const d:any=buildDashboard(track,stats,bookmarks,sessions,difficulty);if(active){const payload=Array.isArray(active.question_payload)?active.question_payload:[];const q=payload[active.current_index];if(q)d.activeSession={id:active.id,mode:active.mode,difficulty:active.difficulty||'all',index:active.current_index,total:active.total,score:active.score,answered:active.answered,question:publicQuestion(q,active.current_index,active.total,bookmarks.includes(q.id))}}return d}

function selectQuestions(track:Track,mode:string,difficulty:Difficulty|'all',stats:any[],bookmarks:string[]){
 const full=banks[track],bank=difficulty==='all'?full:full.filter(q=>q.difficulty===difficulty),statsMap=new Map(stats.map((x:any)=>[x.question_id,x]));let pool=[...bank];
 if(mode==='missed')pool=bank.filter(q=>statsMap.get(q.id)?.last_result===false);
 if(mode==='marked')pool=bank.filter(q=>bookmarks.includes(q.id));
 if(mode==='learn')pool.sort((a,b)=>{const A:any=statsMap.get(a.id),B:any=statsMap.get(b.id);const ad=A?new Date(A.due_at).getTime():0,bd=B?new Date(B.due_at).getTime():0;const aDue=!A||ad<=Date.now(),bDue=!B||bd<=Date.now();if(aDue!==bDue)return aDue?-1:1;if(!A!==!B)return !A?-1:1;return Number(A?.mastery||0)-Number(B?.mastery||0)});else pool=shuffle(pool);
 const limit=mode==='learn'?20:mode==='exam'?Math.min(60,pool.length):Math.min(25,pool.length);return pool.slice(0,limit).map(prepareQuestion);
}
function sessionSummary(s:any,payload:any[],track:Track){
 const answered=payload.filter(x=>typeof x.result==='boolean'),areas=new Map<string,{area:string;correct:number;total:number}>(),standards=new Map<string,{code:string;correct:number;total:number;doc:string;type:string}>();
 answered.forEach(x=>{const a=areas.get(x.area)||{area:x.area,correct:0,total:0};a.total++;if(x.result)a.correct++;areas.set(x.area,a);const st=standards.get(x.standardCode)||{code:x.standardCode,correct:0,total:0,doc:x.standardDoc,type:x.standardType};st.total++;if(x.result)st.correct++;standards.set(x.standardCode,st)});
 const areaResults=[...areas.values()].map(v=>({...v,percent:Math.round(v.correct/v.total*100)})).sort((a,b)=>a.percent-b.percent),standardResults=[...standards.values()].map(v=>({...v,percent:Math.round(v.correct/v.total*100)})).sort((a,b)=>a.percent-b.percent),percent=s.total?Math.round(Number(s.score||0)/Number(s.total)*100):0,passing=percent>=Number(trackMeta[track].passingScore||70);
 return {id:s.id,mode:s.mode,difficulty:s.difficulty||'all',score:Number(s.score||0),total:Number(s.total||payload.length),percent,grade:grade(percent),passing,passingScore:trackMeta[track].passingScore,areaResults,standardResults,weakestArea:areaResults[0]?.area||null,weakestStandard:standardResults[0]?.code||null,review:answered.filter(x=>!x.result).map(x=>({id:x.id,area:x.area,prompt:x.prompt,selected:x.selected,correctIndex:x.correct,correctAnswer:x.options[x.correct],explanation:x.explanation,reference:x.reference,source:x.source,sourceUrl:x.sourceUrl||null,figureRef:x.figureRef||null,choiceExplanations:Array.isArray(x.choiceExplanations)?x.choiceExplanations:null,standardCode:x.standardCode,standardDoc:x.standardDoc,standardType:x.standardType,difficulty:x.difficulty}))};
}

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(!['GET','POST'].includes(req.method))return json(405,{error:'Method not allowed'});
 const base=(Deno.env.get('SUPABASE_URL')||'').replace(/\/+$/,'');const anon=Deno.env.get('SUPABASE_ANON_KEY')||'';const service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!base||!anon||!service)return json(503,{error:'Written Prep is not configured.'});
 const user=await authUser(base,anon,req);if(!user)return json(401,{error:'A free PilotDesk account is required to use Written Prep.',code:'account_required'});const h={apikey:service,Authorization:`Bearer ${service}`,'Content-Type':'application/json'};
 if(req.method==='GET'){const u=new URL(req.url),track=validTrack(u.searchParams.get('track')),difficulty=validDifficulty(u.searchParams.get('difficulty'));return json(200,await dashboard(base,h,user.id,track,difficulty))}
 let body:any;try{body=await req.json()}catch{return json(400,{error:'Invalid JSON'})}const action=String(body?.action||''),track=validTrack(body?.track),difficulty=validDifficulty(body?.difficulty);
 try{
  if(action==='start'){
   const mode=validMode(body?.mode),[stats,bookmarks]=await Promise.all([getStats(base,h,user.id,track),getBookmarks(base,h,user.id,track)]),questions=selectQuestions(track,mode,difficulty,stats,bookmarks);if(!questions.length)return json(409,{error:mode==='missed'?'You have no missed questions in this track/difficulty yet.':mode==='marked'?'You have no marked questions in this track/difficulty yet.':'No questions are available for this mode.'});
   const ins=await rest(base,h,'written_prep_sessions?select=*',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:user.id,track,mode,difficulty,question_payload:questions,current_index:0,score:0,answered:0,total:questions.length})});if(!ins.ok)return json(500,{error:'Unable to start a study session.'});const rows=await ins.json(),s=rows[0];
   return json(200,{session:{id:s.id,track,mode,difficulty,index:0,total:s.total,simulatedMinutes:mode==='exam'?Math.max(15,Math.round(trackMeta[track].officialMinutes*s.total/trackMeta[track].officialQuestions)):null,officialTest:trackMeta[track],question:publicQuestion(questions[0],0,questions.length,bookmarks.includes(questions[0].id))}})
  }
  if(action==='answer'){
   const sessionId=String(body?.sessionId||''),choice=Number(body?.choice);if(!sessionId||!Number.isInteger(choice))return json(400,{error:'Choose an answer first.'});const sr=await rest(base,h,`written_prep_sessions?select=*&id=eq.${enc(sessionId)}&user_id=eq.${enc(user.id)}&limit=1`);if(!sr.ok)return json(500,{error:'Unable to load session.'});const rows=await sr.json(),s=rows[0];if(!s)return json(404,{error:'Study session not found.'});if(s.completed_at)return json(409,{error:'This study session is already complete.'});
   const payload=Array.isArray(s.question_payload)?s.question_payload:[],idx=Number(s.current_index||0),qq:any=payload[idx];if(!qq)return json(409,{error:'No unanswered question remains.'});if(choice<0||choice>=qq.options.length)return json(400,{error:'Invalid answer choice.'});const correct=choice===qq.correct;qq.selected=choice;qq.result=correct;qq.answeredAt=nowIso();
   const statRes=await rest(base,h,`written_prep_stats?select=*&user_id=eq.${enc(user.id)}&track=eq.${track}&question_id=eq.${enc(qq.id)}&limit=1`),statRows=statRes.ok?await statRes.json():[],old=statRows[0]||null,total=Number(old?.total_count||0)+1,corr=Number(old?.correct_count||0)+(correct?1:0),streak=correct?Number(old?.correct_streak||0)+1:0,m=mastery(corr,total,streak);
   const up=await rest(base,h,'written_prep_stats?on_conflict=user_id,track,question_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:user.id,track,question_id:qq.id,skill_area:qq.area,standard_code:qq.standardCode,standard_doc:qq.standardDoc,difficulty:qq.difficulty,correct_count:corr,total_count:total,correct_streak:streak,last_result:correct,mastery:m,due_at:nextDue(streak,correct),last_seen_at:nowIso(),updated_at:nowIso()})});if(!up.ok)return json(500,{error:'Unable to save answer progress.'});
   const nextIdx=idx+1,newScore=Number(s.score||0)+(correct?1:0),done=nextIdx>=payload.length,completedAt=done?nowIso():null,patch=await rest(base,h,`written_prep_sessions?id=eq.${enc(sessionId)}&user_id=eq.${enc(user.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({question_payload:payload,current_index:nextIdx,score:newScore,answered:nextIdx,completed_at:completedAt,updated_at:nowIso()})});if(!patch.ok)return json(500,{error:'Unable to advance study session.'});const pr=await patch.json(),updated=pr[0]||{...s,score:newScore,answered:nextIdx,total:payload.length};
   const bookmarks=await getBookmarks(base,h,user.id,track),feedback=s.mode==='exam'&&!done?null:{correct,selected:choice,correctIndex:qq.correct,correctAnswer:qq.options[qq.correct],explanation:qq.explanation,reference:qq.reference,source:qq.source,sourceUrl:qq.sourceUrl||null,figureRef:qq.figureRef||null,choiceExplanations:Array.isArray(qq.choiceExplanations)?qq.choiceExplanations:null,mastery:m,standardCode:qq.standardCode,standardDoc:qq.standardDoc,standardType:qq.standardType,difficulty:qq.difficulty};
   if(done){const d=await dashboard(base,h,user.id,track,validDifficulty(s.difficulty));return json(200,{done:true,feedback,summary:sessionSummary(updated,payload,track),dashboard:d})}
   return json(200,{done:false,feedback,nextQuestion:publicQuestion(payload[nextIdx],nextIdx,payload.length,bookmarks.includes(payload[nextIdx].id)),progress:{score:newScore,answered:nextIdx,total:payload.length}})
  }
  if(action==='bookmark'){
   const questionId=String(body?.questionId||''),marked=Boolean(body?.marked);if(!banks[track].some(x=>x.id===questionId))return json(400,{error:'Unknown question.'});if(marked){const r=await rest(base,h,'written_prep_bookmarks?on_conflict=user_id,track,question_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:user.id,track,question_id:questionId})});if(!r.ok)return json(500,{error:'Unable to mark question.'})}else{const r=await rest(base,h,`written_prep_bookmarks?user_id=eq.${enc(user.id)}&track=eq.${track}&question_id=eq.${enc(questionId)}`,{method:'DELETE'});if(!r.ok)return json(500,{error:'Unable to unmark question.'})}return json(200,{ok:true,marked})
  }
  if(action==='discard'){const sessionId=String(body?.sessionId||'');if(!sessionId)return json(400,{error:'Session required.'});const r=await rest(base,h,`written_prep_sessions?id=eq.${enc(sessionId)}&user_id=eq.${enc(user.id)}&completed_at=is.null`,{method:'DELETE'});return r.ok?json(200,{ok:true}):json(500,{error:'Unable to discard session.'})}
  return json(400,{error:'Unknown action.'});
 }catch(error){console.error('written-prep',error);return json(500,{error:'Written Prep is temporarily unavailable.'})}
});
