-- PilotDesk account foundation
-- Safe to run in a Supabase project using the SQL editor or migrations.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text check (char_length(display_name) <= 80),
  avatar_url text,
  pilot_stage text check (pilot_stage in ('student','private','instrument','commercial','cfi','atp','other')),
  home_airport text check (char_length(home_airport) <= 8),
  xp integer not null default 0 check (xp >= 0),
  level integer not null default 1 check (level >= 1),
  current_streak integer not null default 0 check (current_streak >= 0),
  longest_streak integer not null default 0 check (longest_streak >= 0),
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_airports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ident text not null check (char_length(ident) between 3 and 8),
  label text check (char_length(label) <= 80),
  created_at timestamptz not null default now(),
  unique(user_id, ident)
);

create table if not exists public.aircraft_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  make_model text check (char_length(make_model) <= 120),
  tail_number text check (char_length(tail_number) <= 20),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_calculations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  tool_slug text not null check (char_length(tool_slug) <= 80),
  title text check (char_length(title) <= 120),
  inputs jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_date date not null,
  challenge_type text not null check (char_length(challenge_type) <= 40),
  score integer not null default 0,
  max_score integer not null default 0,
  xp_awarded integer not null default 0,
  completed_at timestamptz not null default now(),
  unique(user_id, challenge_date, challenge_type)
);

create index if not exists idx_profiles_created_at on public.profiles(created_at desc);
create index if not exists idx_saved_airports_user on public.saved_airports(user_id);
create index if not exists idx_aircraft_profiles_user on public.aircraft_profiles(user_id);
create index if not exists idx_saved_calculations_user_created on public.saved_calculations(user_id, created_at desc);
create index if not exists idx_daily_progress_user_date on public.daily_progress(user_id, challenge_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (
    new.id,
    nullif(coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''), ''),
    nullif(coalesce(new.raw_user_meta_data->>'avatar_url', ''), '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists aircraft_profiles_updated_at on public.aircraft_profiles;
create trigger aircraft_profiles_updated_at before update on public.aircraft_profiles
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.saved_airports enable row level security;
alter table public.aircraft_profiles enable row level security;
alter table public.saved_calculations enable row level security;
alter table public.daily_progress enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "saved_airports_select_own" on public.saved_airports;
drop policy if exists "saved_airports_insert_own" on public.saved_airports;
drop policy if exists "saved_airports_update_own" on public.saved_airports;
drop policy if exists "saved_airports_delete_own" on public.saved_airports;
drop policy if exists "aircraft_profiles_select_own" on public.aircraft_profiles;
drop policy if exists "aircraft_profiles_insert_own" on public.aircraft_profiles;
drop policy if exists "aircraft_profiles_update_own" on public.aircraft_profiles;
drop policy if exists "aircraft_profiles_delete_own" on public.aircraft_profiles;
drop policy if exists "saved_calculations_select_own" on public.saved_calculations;
drop policy if exists "saved_calculations_insert_own" on public.saved_calculations;
drop policy if exists "saved_calculations_delete_own" on public.saved_calculations;
drop policy if exists "daily_progress_select_own" on public.daily_progress;

-- Profiles. Users may read their profile and edit only non-progression columns.
create policy "profiles_select_own" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "profiles_update_own" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

-- Saved airports
create policy "saved_airports_select_own" on public.saved_airports for select to authenticated using (auth.uid() = user_id);
create policy "saved_airports_insert_own" on public.saved_airports for insert to authenticated with check (auth.uid() = user_id);
create policy "saved_airports_update_own" on public.saved_airports for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "saved_airports_delete_own" on public.saved_airports for delete to authenticated using (auth.uid() = user_id);

-- Aircraft profiles
create policy "aircraft_profiles_select_own" on public.aircraft_profiles for select to authenticated using (auth.uid() = user_id);
create policy "aircraft_profiles_insert_own" on public.aircraft_profiles for insert to authenticated with check (auth.uid() = user_id);
create policy "aircraft_profiles_update_own" on public.aircraft_profiles for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "aircraft_profiles_delete_own" on public.aircraft_profiles for delete to authenticated using (auth.uid() = user_id);

-- Saved calculations
create policy "saved_calculations_select_own" on public.saved_calculations for select to authenticated using (auth.uid() = user_id);
create policy "saved_calculations_insert_own" on public.saved_calculations for insert to authenticated with check (auth.uid() = user_id);
create policy "saved_calculations_delete_own" on public.saved_calculations for delete to authenticated using (auth.uid() = user_id);

-- Daily progression is readable by its owner. Writes are reserved for trusted server logic so clients cannot award themselves XP.
create policy "daily_progress_select_own" on public.daily_progress for select to authenticated using (auth.uid() = user_id);

revoke all on public.profiles from authenticated;
revoke all on public.saved_airports from authenticated;
revoke all on public.aircraft_profiles from authenticated;
revoke all on public.saved_calculations from authenticated;
revoke all on public.daily_progress from authenticated;

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, avatar_url, pilot_stage, home_airport, last_seen_at) on public.profiles to authenticated;
grant select, insert, update, delete on public.saved_airports to authenticated;
grant select, insert, update, delete on public.aircraft_profiles to authenticated;
grant select, insert, delete on public.saved_calculations to authenticated;
grant select on public.daily_progress to authenticated;
grant usage, select on sequence public.saved_airports_id_seq to authenticated;
grant usage, select on sequence public.daily_progress_id_seq to authenticated;
