-- PilotDesk Daily retention foundation.
-- Applied to production through Supabase on 2026-09-14.

alter table public.daily_progress add column if not exists challenge_key text;
alter table public.daily_progress add column if not exists perfect boolean not null default false;
alter table public.profiles add column if not exists last_challenge_date date;
alter table public.profiles add column if not exists daily_completions integer not null default 0 check (daily_completions >= 0);

create table if not exists public.user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  badge_key text not null check (char_length(badge_key) between 1 and 64),
  earned_at timestamptz not null default now(),
  unique(user_id, badge_key)
);

create index if not exists idx_daily_progress_date_type on public.daily_progress(challenge_date desc, challenge_type);
create index if not exists idx_daily_progress_user_daily on public.daily_progress(user_id, challenge_date desc) where challenge_type = 'pilot_daily';
create index if not exists idx_user_badges_user on public.user_badges(user_id, earned_at desc);

alter table public.user_badges enable row level security;
drop policy if exists "user_badges_select_own" on public.user_badges;
create policy "user_badges_select_own" on public.user_badges for select to authenticated using (auth.uid() = user_id);
revoke all on public.user_badges from authenticated;
grant select on public.user_badges to authenticated;
grant usage, select on sequence public.user_badges_id_seq to authenticated;
revoke update (xp, level, current_streak, longest_streak, last_challenge_date, daily_completions) on public.profiles from authenticated;

create or replace function public.complete_pilot_daily(
  p_user_id uuid,
  p_challenge_date date,
  p_challenge_key text,
  p_score integer,
  p_max_score integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.profiles%rowtype;
  existing public.daily_progress%rowtype;
  new_streak integer;
  new_longest integer;
  new_completions integer;
  awarded integer;
  new_xp integer;
  new_level integer;
  is_perfect boolean;
begin
  if p_user_id is null or p_challenge_date is null or p_challenge_key is null then raise exception 'invalid daily completion input'; end if;
  if p_max_score < 1 or p_score < 0 or p_score > p_max_score then raise exception 'invalid daily score'; end if;

  select * into p from public.profiles where id = p_user_id for update;
  if not found then raise exception 'profile not found'; end if;

  select * into existing from public.daily_progress
  where user_id = p_user_id and challenge_date = p_challenge_date and challenge_type = 'pilot_daily'
  limit 1;
  if found then
    return jsonb_build_object('alreadyCompleted',true,'score',existing.score,'maxScore',existing.max_score,'xpAwarded',existing.xp_awarded,'streak',p.current_streak,'longestStreak',p.longest_streak,'xp',p.xp,'level',p.level,'dailyCompletions',p.daily_completions,'perfect',existing.perfect);
  end if;

  new_streak := case when p.last_challenge_date = p_challenge_date - 1 then p.current_streak + 1 else 1 end;
  new_longest := greatest(p.longest_streak, new_streak);
  new_completions := p.daily_completions + 1;
  is_perfect := p_score = p_max_score;
  awarded := 15 + (p_score * 10) + (case when is_perfect then 15 else 0 end) + least(greatest(new_streak - 1, 0) * 2, 20);
  new_xp := p.xp + awarded;
  new_level := greatest(1, floor(new_xp / 250.0)::integer + 1);

  insert into public.daily_progress(user_id,challenge_date,challenge_type,challenge_key,score,max_score,xp_awarded,perfect)
  values(p_user_id,p_challenge_date,'pilot_daily',p_challenge_key,p_score,p_max_score,awarded,is_perfect);

  update public.profiles set xp=new_xp,level=new_level,current_streak=new_streak,longest_streak=new_longest,last_challenge_date=p_challenge_date,daily_completions=new_completions,updated_at=now() where id=p_user_id;

  insert into public.user_badges(user_id,badge_key) values (p_user_id,'first_daily') on conflict do nothing;
  if is_perfect then insert into public.user_badges(user_id,badge_key) values (p_user_id,'perfect_daily') on conflict do nothing; end if;
  if new_streak >= 7 then insert into public.user_badges(user_id,badge_key) values (p_user_id,'streak_7') on conflict do nothing; end if;
  if new_streak >= 30 then insert into public.user_badges(user_id,badge_key) values (p_user_id,'streak_30') on conflict do nothing; end if;
  if new_completions >= 25 then insert into public.user_badges(user_id,badge_key) values (p_user_id,'daily_25') on conflict do nothing; end if;

  return jsonb_build_object('alreadyCompleted',false,'score',p_score,'maxScore',p_max_score,'xpAwarded',awarded,'streak',new_streak,'longestStreak',new_longest,'xp',new_xp,'level',new_level,'dailyCompletions',new_completions,'perfect',is_perfect);
end;
$$;

revoke all on function public.complete_pilot_daily(uuid,date,text,integer,integer) from public, anon, authenticated;
grant execute on function public.complete_pilot_daily(uuid,date,text,integer,integer) to service_role;
