'use strict';
const W=require('../assets/winds-aloft-core.js'),N=require('../assets/navlog-core.js');
const AWC='https://aviationweather.gov/api/data/',cache=new Map();
async function cached(key,url,json,ttl){const old=cache.get(key);if(old&&old.until>Date.now())return old.promise;const promise=(async()=>{const r=await fetch(url,{headers:{'User-Agent':'PilotDesk/3.0 (+https://www.pilot-desk.com)'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('Winds provider unavailable. Try again later.');return json?r.json():r.text()})();cache.set(key,{until:Date.now()+ttl,promise});try{return await promise}catch(e){cache.delete(key);throw e}}
function midpoint(p,q){const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI,a=rad(p.lat),b=rad(q.lat),d=rad(q.lon-p.lon),x=Math.cos(b)*Math.cos(d),y=Math.cos(b)*Math.sin(d);return{lat:deg(Math.atan2(Math.sin(a)+Math.sin(b),Math.hypot(Math.cos(a)+x,y))),lon:p.lon+deg(Math.atan2(y,Math.cos(a)+x))}}
module.exports=async(req,res)=>{
res.setHeader('Cache-Control','no-store');if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({error:'Use POST to request route winds.'})}
try{const body=typeof req.body==='string'?JSON.parse(req.body):req.body,{points,altitude,departureUtc,arrivalUtc}=body||{};const departure=Date.parse(departureUtc),arrival=Date.parse(arrivalUtc);if(!Array.isArray(points)||points.length<2||points.length>30||!Number.isFinite(altitude)||altitude<3000||altitude>39000||!Number.isFinite(departure)||!Number.isFinite(arrival)||arrival<departure) return res.status(400).json({error:'Build a route, enter UTC departure and altitude from 3,000 to 39,000 ft MSL.'});for(const p of points){N.distanceCourse(p,p);if(p.lat<24||p.lat>50||p.lon< -125||p.lon> -66)return res.status(400).json({error:'Forecast winds currently cover the contiguous United States only.'})}
const results=await Promise.allSettled(['06','12','24'].map(async cycle=>W.parse(await cached(cycle,AWC+'windtemp?region=us&level=low&fcst='+cycle,false,300000))));const bulletins=results.filter(r=>r.status==='fulfilled').map(r=>r.value);if(!bulletins.length)throw new Error('Forecast winds provider unavailable. Try again later.');const bulletin=bulletins.filter(b=>departure>=b.start&&arrival<=b.end&&b.baseAt<=Date.now()&&Date.now()-b.baseAt<36*3600000).sort((a,b)=>b.baseAt-a.baseAt)[0];if(!bulletin)return res.status(422).json({error:'No available bulletin covers the full planned flight. Change the departure time or enter winds manually.'});const ids=[...new Set(bulletin.stations.map(s=>'K'+s.id))];const info=await cached('stations:'+ids.join(','),AWC+'stationinfo?format=json&ids='+ids.join(','),true,86400000);if(!Array.isArray(info))throw new Error('Winds station positions unavailable.');const located=bulletin.stations.map(s=>({...s,position:info.find(p=>p.icaoId==='K'+s.id||p.id==='K'+s.id)})).filter(s=>Number.isFinite(s.position?.lat)&&Number.isFinite(s.position?.lon));
const legs=points.slice(0,-1).map((p,i)=>{const q=points[i+1],mid=midpoint(p,q);const nearest=located.map(s=>({...s,distance:N.distanceCourse(mid,s.position).distance})).sort((a,b)=>a.distance-b.distance)[0];if(!nearest||nearest.distance>200)throw new Error('No winds station within 200 NM of a leg midpoint. Enter that route’s winds manually.');const wind=W.sample(nearest.levels,altitude);return{...wind,station:nearest.id,stationDistanceNm:nearest.distance}});
return res.status(200).json({source:'AWC / NWS winds and temperatures aloft',sourceUrl:AWC+'windtemp?region=us&level=low',fetchedAt:new Date().toISOString(),baseAt:bulletin.baseAt,validAt:bulletin.validAt,start:bulletin.start,end:bulletin.end,altitude,legs});
}catch(e){return res.status(502).json({error:e instanceof SyntaxError?'Invalid request body.':['TypeError','TimeoutError','AbortError'].includes(e.name)?'Forecast winds provider unavailable. Try again later.':e.message||'Forecast winds unavailable.'})}
};
